### ISSUE TITLE
Unhandled exception when opening

### ISSUE THREAD

**Issue by shrubin** [Assistant/ModAssistant#1]
Downloaded v1.0.3 and getting this error when I try to run: Object reference not set to an instance of an object. The processes also continued running in the background after the crash.

**Comment by Assistant** [comment]
Could you PM me on Discord? I can't reproduce the issue so I'd like to test some things and see what works.

**Comment by shrubin** [comment]
Hey sorry for the delay, here it is:
<img width="327" alt="Capture" src="https://user-images.githubusercontent.com/6194300/58114894-aa67d180-7bad-11e9-9ff5-1895a3436f3e.PNG">
Seems like it can't find my install directory?

**Comment by shrubin** [comment]
Fixed, it now asks for my install directory

**Comment by Assistant** [comment]
Yup, I sneaked in a try block so that it doesn't crash in the latest update. It should only ask for install directory once.
