### ISSUE TITLE
crash when pressing headpats/Hugs button

### ISSUE THREAD

**Issue by Pikotaro** [Assistant/ModAssistant#102]
![Screenshot (691)](https://user-images.githubusercontent.com/15929767/77104258-085a8500-6a1c-11ea-84d4-31cdb4014b19.png) I´ve attached a screenshot of the error message

**Comment by Majorkrabbe** [comment]
Got the same prob

**Comment by lolPants** [comment]
Already fixed as of b1a500118888bcbb30fd41cc0488db4308a9639a, just waiting on a release.
