### ISSUE TITLE
game versions list not downloading

### ISSUE THREAD

**Issue by JorindaBecker** [Assistant/ModAssistant#105]
I'm getting an error message when I started up the ModAssitant. It also tells me it could not download versions list, so the mods tab is disabled. 

![error](https://user-images.githubusercontent.com/60412122/77655881-abd5f900-6f38-11ea-86e7-dda7d3ee3846.jpg)

**Comment by tehbab00n** [comment]
i have the same thing, nothing seems to work! i tried reinstal and other versions. help us out pls :)

**Comment by Jverm84** [comment]
Can someone please contact me on how to fix this. I finally updated thinking things would be figured out and I’m extremely disappointed. Someone please email me at this email on how to do it or send me a link for as easy patch. Either jverminski84@gmail.com or DareDevil35@protonmail.com
