### ISSUE TITLE
I can't change the directory of the install folder

### ISSUE THREAD

**Issue by TheRealBigo** [Assistant/ModAssistant#12]
So when I try to change the directory of my install folder it doesn't do anything. This is what it tells me before I click save.
![Screenshot_19](https://user-images.githubusercontent.com/42416795/58352944-11e68100-7e3b-11e9-9726-db62058bbd0f.png) After click save the directory stays the same as it was before and if I try to install the mods it installs them in the old install folder.

**Comment by megalon** [comment]
As a work around, looks like for now if you select the new location, then restart the application, it'll set the folder correctly.

**Comment by TheRealBigo** [comment]
Alright thanks!

**Comment by megalon** [comment]
I'm not able to completely reproduce this.
It looks like it does save the install directory you select, but it just doesn't show the new filepath in the settings window, but if you click "Install / Update" it will install to the newly selected filepath anyway.

BSIPA doesn't immediately place mods into the Plugins folder upon download anymore. They go into the "Pending" folder `Beat Saber\IPA\Pending\Plugins`
Then when you run the game they are copied over to the `Beat Saber\Plugins` folder.
I wonder if that's what you're experiencing here.
