### ISSUE TITLE
Forces re-install (downgrading) when a newer version of the mod is manually installed

### ISSUE THREAD

**Issue by oscardianno** [Assistant/ModAssistant#121]
I manually installed BSIPA, in this case, because I was having problems with the game not loading the mods. And apparently, this newer version hasn't been pushed to ModAssistant yet.
However, ModAssistant doesn't recognize this as a newer version and forces re-installation (because it's not possible to uncheck it), which ends up in downgrading the mod's version. As you can see, the installed mod's version is in crossed red numbers
![BSIPA1](https://user-images.githubusercontent.com/46467428/79071741-ef539580-7ca2-11ea-9299-7b20c602afe7.png)
I wanted to install Mapping Extensions. As I couldn't uncheck BSIPA, the "newest" version available in ModAssistant was downloaded and replaced the installed version.
![BSIPA2](https://user-images.githubusercontent.com/46467428/79071774-275ad880-7ca3-11ea-8453-abcd8b6684d4.png)

**Comment by laundmo** [comment]
im having the same problem

it should not bother with "updating" if the version number is higher
