### ISSUE TITLE
MA wont start

### ISSUE THREAD

**Issue by Caligula521** [Assistant/ModAssistant#122]
First time trying to use mod assistant. when  i open the exe nothing happens. it does however show up in my task manager. sometimes it reads as suspended in TM. running win10

**Comment by megalon** [comment]
Are there are any error messages that appear?
If you have any anti-virus, try disabling it and running again.

**Comment by qua1121** [comment]
Same problem. Diabled my anti-virus but still nothing showing up.
Intel i7, Geforce, Vive Pro Wireless.

**Comment by qua1121** [comment]
Okay, solved the problem by downloading v1.1.10.
