### ISSUE TITLE
ModAssistant installs mods I do no want, glitch/error

### ISSUE THREAD

**Issue by TakoYachty** [Assistant/ModAssistant#123]
In Mod Assistant v1.1.5, the option to save selected mods and check selected mods is broken.
![bad](https://user-images.githubusercontent.com/20880653/79180025-c5db5c80-7dbd-11ea-86e9-d73b2a9426b9.png)

As you can see in the photo below, is the list of mods I've selected. Very light- no fancy gizmos.
![good](https://user-images.githubusercontent.com/20880653/79179952-a3494380-7dbd-11ea-9aed-306942997650.png)

Saving the option for these mods will actually put two mods on queue that I do not want, which will then install them anyways even if you uninstall them or uncheck them. It even erroneously  lists bogus versions of the mods that doesn't even exist yet.

![bad 2](https://user-images.githubusercontent.com/20880653/79180046-ce339780-7dbd-11ea-952a-fe621b94d372.png)

I have no idea why this happens but I have successfully replicated it three times.

**Comment by Encline** [comment]
I have the same issue as well. The same mods "RandomSongPlayer" and "Custom Notes" are selected whenever I open the Mod Assistant.

**Comment by RafaelSchridi** [comment]
Yeah same here, It thinks it has version 1.8.0 of Custom Notes installed but I don't have it at all.
![image](https://user-images.githubusercontent.com/11460682/79855837-cd0cf680-83cb-11ea-9ac5-dd87991a4845.png)
