### ISSUE TITLE
Remove Anti-Piracy DRM

### ISSUE THREAD

**Issue by yiays** [Assistant/ModAssistant#124]
A mod manager has no business protecting the intelectual property of a company that it isn't associated with. I don't understand what the reasoning for this is. If Beat Games wanted to prevent piracy as much as you do, they'd do it themselves.

I'm one among many people who bought Beat Saber legitimately on one platform and want to play on another. I paid for the PS4 edition at full price and got a PC VR headset later, I don't play much on PC so I don't see any ethical or logical reason to buy the game twice.

**Comment by yiays** [comment]
In that case, I'll be releasing auto-updating builds without DRM in my fork.

Anyone that doesn't happen to agree with your opinions on piracy can get ModAssistant from here; https://github.com/yiays/ModAssistant-DRMless

**Comment by Assistant** [comment]
This project is MIT licensed, so you're free to do as you wish. Advertising it in here, BSMG, or similar avenues will not be allowed, though.

**Comment by yiays** [comment]
Yes, I did take into account the license before making a modified clone. It is dissapointing that you don't seem to be interested in discussing a solution that doesn't require a fork, or even justifying your decision.

I understand it's a divisive issue, but try and see my point of view;
People who pirate games fit into a number of categories...
 - *People who want to try a game before buying it* - they wouldn't buy the game first no matter what, and intend on paying for it if they like it. **These people are a net positive on the developers' revenue.**
 - *People who already bought the game on a different store* - they've already bought the game and are just moving platforms, you can't expect them to buy their entire library back. **These people have no negative impact on the developers.**
 - *People who are unable to run the game with DRM* - there are always going to be edge cases (linux gamers, for example) that might not be able to run the paid version of a game, they've either already bought the game or never will. **These people have no negative impact on the developers**

If a pirate has a positive experience with a game and plays it a lot, they'll buy the full version for the convenience of automatic updates, achievements and save data cloud sync. Or they won't. Either way, the developers aren't losing money over it because they wouldn't have bought it otherwise.

Considering ModAssistant is essentially the only mod manager, and Beat Saber mods are almost essential for most people, you're in a position of power. I'd like to suggest you use that power to encourage pirates to consider buying the game rather than shunning them.

**Comment by Assistant** [comment]
Here's not the place to discuss it, but my PMs are open on Discord if you do want to. `Assistant#8431`

**Comment by ttimasdf** [comment]
Whatever the reason is, it's an open source project. You are always free to mod the mod installer your self. While the community is open for discussion, but piracy is never encouraged in any way, so if the maintainers decide to keep you out, you have to do it yourself.

A hint, use [dnSpy](https://github.com/dnSpy/dnSpy).
