### ISSUE TITLE
Mod assistant not retaining user settings

### ISSUE THREAD

**Issue by ancapgamer** [Assistant/ModAssistant#13]
Not sure if this is a localized issue to me or happening to others (i did see someone else say the same in the support channel in discord). The user settings in options seem to not stay checked after the program is closed or the pc is rebooted. If this is intended, cool. If not, it's just an annoyance.

**Comment by Assistant** [comment]
Which settings are you talking about? The only settings that aren't "saved" are the OneClick Install ones, because those ones detect if the registry key is set instead.

**Comment by ancapgamer** [comment]
![settings](https://user-images.githubusercontent.com/42419336/58374735-95b67100-7f00-11e9-8d2b-75d587ed49b1.PNG)

These settings, i have them checked now. But I have to re select them each time.

**Comment by Assistant** [comment]
Those should be getting saved, where are you running it from?

**Comment by ancapgamer** [comment]
I have the file in my downloads folder and i run it from there. Do i need to run it or set it as admin?

**Comment by Assistant** [comment]
You shouldn't have to run it as admin. 
I released a new version with improved settings handling, I'm not sure if that'll fix the issue you're having but it's worth a try

**Comment by ancapgamer** [comment]
Seems to have resolved the issue, thanks!
