### ISSUE TITLE
Update Outdated Mods

### ISSUE THREAD

**Issue by MdotAmaan** [Assistant/ModAssistant#137]
It'd be nice if, instead of reinstalling every mod to update just one, to have something which checks for outdated mods and only installs those mods.

**Comment by Jverm84** [comment]
Obviously that should be the case. Simple things like this should be standard and not the exception

**Comment by Parapass** [comment]
It's possible, but it would need integration with BSIPA to check for new game versions + the app would have to be running before you start the game (i think).

**Comment by megalon** [comment]
@Parapass I think you're misunderstanding the question. They are saying that MA shouldn't reinstall mods that are already installed and up to date.

Currently MA only skips installing a mod when a newer version is already installed.
It would be easy to skip installing mods that are already installed and up to date, but Assistant and I reasoned that simply reinstalling all mods each time would at worst make you wait a few more seconds for nothing, and at best it would fix corrupted files.

We could certainly make it optional to reinstall all mods, I think it'd be a good addition.
I'd like to ask why you think it should though. Is the additional wait to reinstall mods significant for you?

**Comment by MdotAmaan** [comment]
The wait time can be significant solely due to custom campaigns, or my isp deciding to throttle me
