### ISSUE TITLE
Unable to download Mod Assistant releases

### ISSUE THREAD

**Issue by MRuth** [Assistant/ModAssistant#138]
While attempting to download the latest 3 releases (1.1.4+), the download link redirects to a `
SignatureDoesNotMatch` error from what appears to be Amazon S3 returned as an XML document.

**Comment by Parapass** [comment]
This is currently an issue with GitHub as of right now. Try checking back in about an hour or so.

**Comment by MRuth** [comment]
Ahh, okay.  Thanks!

**Comment by Parapass** [comment]
Downloads are fixed now.
