### ISSUE TITLE
Keep BeatSaver and ScoreSaber mods unchecked

### ISSUE THREAD

**Issue by kuraha4** [Assistant/ModAssistant#154]
Is it possible to add an ability to keep unchecked states of these mods? 

- BeatSaverVoting
- ScoreSaber
- BeatSaverDownloader

I don't want to uncheck these whenever launch ModAssistant. "Save Selected Mods" option doesn't help. Thanks.

**Comment by Parapass** [comment]
[ModAssistant.zip](https://github.com/Assistant/ModAssistant/files/4645713/ModAssistant.zip)
try this build

**Comment by kuraha4** [comment]
It works as I wanted. Thank you so much.
