### ISSUE TITLE
Looking for BeatSaber install in wrong location

### ISSUE THREAD

**Issue by csprocket777** [Assistant/ModAssistant#16]
When I run ModAssistant, it gives me an error that indicates that it's looking on the C Drive, except that I have installed it on the D drive. How do I tell ModAssistant where the installation directory is?

**Comment by lucawen** [comment]
Click inside the 'Options' menu, and will be a 'Install Folder' location for you select your game location.

**Comment by Kojima13** [comment]
I have the same problem here. There is no "Options" menu since we can't even open the executable.
I had Beat Saber installed on my F drive then unistalled and installed on another drive and [this error](https://puu.sh/DDNmo/e91b071210.jpg) occured.

**Comment by Assistant** [comment]
@Kojima13 That happens if you move uninstall the game but not completely, it'll be fixed in the next release.
