### ISSUE TITLE
One click install silently failing

### ISSUE THREAD

**Issue by GhostofGoes** [Assistant/ModAssistant#160]
One click installs from bsaber.com have not worked since the latest update (last install that worked for me was on 05/01)

**Comment by GhostofGoes** [comment]
This appears to be fixed in 56d21f1 (had to comment out a message box but at least it works)

Once the fix makes its way into a release I'll close the issue

**Comment by DomDom3333** [comment]
Disabeling and re-enabeling one click installs fixed it for me

**Comment by GhostofGoes** [comment]
It's been working for a while, closing this.
