### ISSUE TITLE
Feature request: option to remove delay before One Click Installer window closes

### ISSUE THREAD

**Issue by chenxiaolong** [Assistant/ModAssistant#166]
Would it be possible to add an option to remove the One Click Installer window close delay or maybe as a command line argument for `--install`? (https://github.com/Assistant/ModAssistant/commit/ec03c8127ba4393a4c8c33183fa0bf978b8d0599#diff-ec33cd5dc117e75e426b7c29ee2a5f3fR115)

Right now, I have a few scripts that download songs by sequentially invoking `beatsaver://<ID>/` URIs with `ShellExecuteEx` and waiting for them to complete. With the recent changes (+ `CloseWindowOnFinish` enabled), there's a 5 second delay between downloading songs.

I'm currently building from source with the delay commented out and wouldn't mind continuing to do so if this is not something that should be implemented. I know ModAssistant is primarily for interactive use.

**Comment by Assistant** [comment]
Would you be ok with it being a setting without any way to change it in program? Meaning you'd have to open appdata and edit it there manually.

**Comment by chenxiaolong** [comment]
Sure, that's perfectly fine for me.

**Comment by Box-Of-Hats** [comment]
How do you enable the CloseWindowOnFinish setting? I'm doing something similar with the commandline but every time I invoke a download it opens a new instance of ModAssistant.exe that doesn't ever close

**Comment by megalon** [comment]
Looking at the commit history, it doesn't look like this feature has been added yet.

**Comment by megalon** [comment]
I believe this feature has been implemented, but this issue never closed.
The delay is off by default, but it can be re-enabled by editing `C:\Users\username\AppData\Local\ModAssistant\ModAssistant.exe_{bunch of characters}\{version}`
