### ISSUE TITLE
Option to select localization in settings

### ISSUE THREAD

**Issue by evonprime** [Assistant/ModAssistant#167]
ModAssistant updated itself from 1.1.6.0 to 1.1.9.0 and decided to switch the localization from English to German for some reason. My OS (Win 10 1903) language is set to English (US), although it was originally installed in German. Region is set to Austria, regional format to German (Austria). Keyboard layout is set to German. So I guess ModAssistant checks the wrong locale setting (region or keyboard maybe). I'd say the best solution would be to let the user select the language via the settings. 

Should not be hard to implement. Haven't coded anything in C#/.NET in many years, otherwise I'd do it myself and create a pull request.

**Comment by Assistant** [comment]
There's a launch option you could use, `--language en`. It doesn't save it currently, but I plan to make it so it does.

**Comment by evonprime** [comment]
Thanks for the info, that works fine. I agree that it would be a good idea to save the selected language though.

**Comment by lukad** [comment]
Ran into the same issue today. This happens because windows handles localization in a _very_ unintuitive way. 

You should be using `CurrentUICulture` instead of `CurrentCulture` to determine the language to be used.

See https://docs.microsoft.com/en-us/archive/blogs/ddietric/yacvcp-yet-another-currentculture-vs-currentuiculture-post

> CurrentUICulture is what Windows refers to as the "display language" (some people also call it "UI language"). It is used by applications (and the OS) to determine which UI resources to load - i.e. (slightly simplified) either the resources for the current UI culture or neutral resources in case there are no resources for the UI culture. Or as the MSDN .NET class reference puts it: The CurrentUICulture is "the CultureInfo that represents the current culture used by the Resource Manager to look up culture-specific resources at run time". A reason (other than testing purposes) to set the UI culture would be to allow the end user to change the display language of a particular application independently regardless of the OS settings. An example for this is the language settings tool that is part of Office 2007.

> CurrentCulture is for formatting strings and is primarily used in ToString() methods and other methods that convert values like numbers or dates into strings. I honestly cannot think of a good reason (other than testing purposes) to set this culture in code (not saying that there are none but they are exceptions).
