### ISSUE TITLE
Game version 1.10 not listed

### ISSUE THREAD

**Issue by baxterp** [Assistant/ModAssistant#172]
Hello, After the recent game update to version 1.10.

That game version is not listed in Mod Assistant

Thanks,

**Comment by Parapass** [comment]
This is a BeatMods problem. It will be fixed soon.

**Comment by macery12** [comment]
sorry dont mean to be rude or rush at all but how long does it normaly take for it to be fixed?

**Comment by urielsalis** [comment]
Most of 1.8.0 mods work

**Comment by chewston** [comment]
Second this. It's telling me 547 songs loaded but none are showing up ingame.

**Comment by baxterp** [comment]
I copied the contents of from the 'old 1.9.1 Plugins' folder into the 'Plugins' folder. This seems to have fixed everything except the scoreboard.

**Comment by baxterp** [comment]
It's fixed well done guys :)
