### ISSUE TITLE
Setting to disable localization (or to choose a language)

### ISSUE THREAD

**Issue by pravic** [Assistant/ModAssistant#174]
Because right now the auto-selected translation is awful - I'd rather stick with English.

**Comment by Anthropomorphed** [comment]
Just wanted to create an issue about it.
Language is automatically changed to language of your ips location (assumption).
Please make it manual. ~~And never go back to auto-selection based on ip~~
Make it auto-select on os language setting at best.
![unknown](https://user-images.githubusercontent.com/25126266/83312823-17c42e80-a214-11ea-97fd-85ecbadc597b.png)
