### ISSUE TITLE
couldn't download version list.

### ISSUE THREAD

**Issue by siddasfaultier** [Assistant/ModAssistant#186]
If I try to accept the rules at the start screen this error appears:

"Could not download versions list. 
Mods tab disabled. Please restart to try again."

I allready cleaned the App-Data folder, reinstalled Beat saber. But there it's not working. 

and there is another error showing up after approx a minute.

![grafik](https://user-images.githubusercontent.com/66469346/83863669-f25b8700-a723-11ea-95d5-20ad2e5eab12.png)

**Comment by Janxe19** [comment]
same here

**Comment by Whoolyy** [comment]
Me to...

**Comment by Whoolyy** [comment]
siddasfaultier put the label bug on this post

**Comment by siddasfaultier** [comment]
> 
> 
> siddasfaultier put the label bug on this post

how do i do that. I'm new to github

**Comment by siddasfaultier** [comment]
It's working again. I think there was a problem with the server...

**Comment by Eevee349** [comment]
BeatMods is up rn and I still can't download the versions list. I've been dealing with this problem for months, I just want to play my custom songs
