### ISSUE TITLE
oneclick windows don't close (IDK if they even install)

### ISSUE THREAD

**Issue by herosilas12** [Assistant/ModAssistant#193]
![Annotation 2020-06-09 074028](https://user-images.githubusercontent.com/36961653/84148550-c93d3e00-aa24-11ea-9e32-532063e947cd.png)
is that intended?

**Comment by herosilas12** [comment]
they do install 
just checked but the window remains open anyways

**Comment by Parapass** [comment]
this appears to be commented in the latest options update, https://github.com/Assistant/ModAssistant/blob/master/ModAssistant/Pages/Options.xaml#L214-L223
it might've broken something in the menu which is why is was commented
