### ISSUE TITLE
mod assistant not saving install folder when closed for all but mods

### ISSUE THREAD

**Issue by tunefullcobra** [Assistant/ModAssistant#196]
simply put whenever I open mod assistant the install folder text line is empty and when I click open folder I get an error message that I will attach as a picture.
this means that one-click installs from beatsaver do not go through, I have not tried modelsaber.
upon closing the error message that pops up when I click open folder the entire program closes
then when I open the program back up the options menu appears and the text box that should have the install folder location in it is blank and the check boxes for "save selected mods", "detect installed mods", and "select installed mods" are unchecked when I know I checked them. though this happens every time I close then re-open the program so I do not believe this is the sole cause
![modassistant](https://user-images.githubusercontent.com/66848249/84544018-54326880-acb1-11ea-95fc-797fa2bf057f.png)

**Comment by tunefullcobra** [comment]
I have tried re downloading mod assistant and the version I am showing in the picture is the latest

**Comment by tunefullcobra** [comment]
I would like to correct that after opening beat saber I have found the songs I was trying to download with the one click installer. so the only problem regarding that is that the one click installer windows don't automatically close

**Comment by megalon** [comment]
I believe this is fixed with the latest version.
Are you still seeing this issue?

**Comment by tunefullcobra** [comment]
I just checked and yes it is fixed. Thank you for your follow up
