### ISSUE TITLE
OneClick Installs do not work

### ISSUE THREAD

**Issue by e00E** [Assistant/ModAssistant#20]
I have the most recent release of mod assistant.

I would like to enable one click installs so I go into the options where I see the text `Enable OneClick Installs` and to the right in yellow `Allows use of OneClick Install links -  Requires Admin`. I do not see a check box or button to press to enable. I tried clicking on various parts of the text but nothing happens and one click install links do not work.

I tried running Mod Assistant as admin but it did not help.

**Comment by Assistant** [comment]
There should be options below it to enable OneClick Installs for `BeatSaver` and `ModelSaber`, you have to check those

**Comment by e00E** [comment]
Ah you're right. I did not make the connection that they are related to that text. Now its obvious.
