### ISSUE TITLE
Beat Saber file path and settings don't appear to be save but function normally.

### ISSUE THREAD

**Issue by Rayn322** [Assistant/ModAssistant#200]
![image](https://user-images.githubusercontent.com/16494880/84968998-9b16c880-b0cc-11ea-87ad-a7445cc67509.png)

This happens whenever I close and reopen mod assistant. Everything works (except for the open folder button) and it installs mods fine but it doesn't display the enabled options correctly.

**Comment by anthonyda** [comment]
+1, I have the same bug :(

**Comment by Rayn322** [comment]
Fixed last update.
