### ISSUE TITLE
Playlist downloader 

### ISSUE THREAD

**Issue by boulders2000** [Assistant/ModAssistant#208]
I don't know if it is intentional or not, but the playlist downloader doesn't work if the playlist is not in the playlists folder. It also doesn't create a playlists folder if there isn't one already

**Comment by megalon** [comment]
I'm unable to reproduce this issue.
What OS are you using?

On my Windows 10 machine, if the Playlists folder doesn't exist, Mod Assistant will create it upon installing a playlist.

**Comment by boulders2000** [comment]
Windows 10, mod assistant version 1.1.13

**Comment by megalon** [comment]
Are you still having this issue?

**Comment by boulders2000** [comment]
Sorry for the late reply, have been on vacation
But I haven't tested it since then, will do so later today and see

**Comment by boulders2000** [comment]
ok so, the playlist not being in playlists folder thing i said is now working. 

but the folder not being there at all is still not working,
like i moved the playlists folder out and tried to download a playlist and it didnt do anything
