### ISSUE TITLE
Error Message and cant download songs

### ISSUE THREAD

**Issue by CanniestRug6** [Assistant/ModAssistant#212]
Most of the time, when i try to install a mod on modassistant, i get a really long error code. it causes me not to be able to download songs most of the time. ill click download, itll start downloading but then the bar will disappear and it still gives me the option to download the song, meaning it wasnt installed. It prevents me from playing online with other people because im unable to download the songs theyre playing. Also, when i start a level, some of the times it wont actually start until a few seconds later. so im just sitting in the level waiting for it to start and waiting for my sabers to spawn. how do i fix this?
![Desktop Screenshot 2020 07 07 - 14 01 09 28](https://user-images.githubusercontent.com/67983184/86850560-1853ae80-c077-11ea-93f2-8f51867e0473.png)

**Comment by Meivyn** [comment]
That's an issue I known about and the user was able to fix it by switching his IP, by installing a VPN for example.

**Comment by lolPants** [comment]
Please refrain from necro'ing old issues.

**Comment by Meivyn** [comment]
Ah sorry, I didn't notice the date.
