### ISSUE TITLE
Internal error 0x01

### ISSUE THREAD

**Issue by ZyphrWind** [Assistant/ModAssistant#218]
I get an error when installing mod to beat saber. Here is the screenshot. 
![IMG_20200725_134427](https://user-images.githubusercontent.com/11292793/88449887-3e51bf00-ce7d-11ea-9797-f97cdca2b932.jpg)

**Comment by Parapass** [comment]
Stop pirating games and the error will be fixed.

**Comment by ZyphrWind** [comment]
I bought the game.. It's not pirated. 




Get Outlook for Android







On Sat, Jul 25, 2020 at 7:51 PM +0800, "Parapass" <notifications@github.com> wrote:















Stop pirating games and the error will be fixed.

**Comment by ZyphrWind** [comment]
The game is working but when i installed mods using mod assistant that is the error i get. 




On Sat, Jul 25, 2020 at 7:51 PM +0800, "Parapass" <notifications@github.com> wrote:















Stop pirating games and the error will be fixed.

**Comment by Parapass** [comment]
Delete your game and reinstall it. Do you have anything else that would require a "steam_emu.ini" file?

**Comment by ZyphrWind** [comment]
Hrmm, i've already done that i've tried uninstalling and reinstalling beat saber a couple of times. The game works as it is but when i install mods that error appears i had to revert back to make it work again.. Nope i dont have anything that needs steam_emu.ini its the first time i've encountered that after i installed mod from mod assistant. 




Get Outlook for Android







On Sun, Jul 26, 2020 at 8:26 PM +0800, "Parapass" <notifications@github.com> wrote:















Delete your game and reinstall it. Do you have anything else that would require a "steam_emu.ini" file?

**Comment by ZyphrWind** [comment]
Does the beat saber mod need the steam_emu.ini?  Why does the error happen only when i install mods using mod aasistant? 




Get Outlook for Android







On Sun, Jul 26, 2020 at 9:42 PM +0800, <alvinzagala@icloud.com> wrote:










Hrmm, i've already done that i've tried uninstalling and reinstalling beat saber a couple of times. The game works as it is but when i install mods that error appears i had to revert back to make it work again.. Nope i dont have anything that needs steam_emu.ini its the first time i've encountered that after i installed mod from mod assistant. 




Get Outlook for Android







On Sun, Jul 26, 2020 at 8:26 PM +0800, "Parapass" <notifications@github.com> wrote:















Delete your game and reinstall it. Do you have anything else that would require a "steam_emu.ini" file?

**Comment by OnSive** [comment]
The error isn't produced by ModAssistant - ModAssistant does neither read nor write the `steam_emu.ini` file.
