### ISSUE TITLE
[Enhancement] Option for deleting the songs from within the game

### ISSUE THREAD

**Issue by bananek** [Assistant/ModAssistant#223]
Is it possible to add an option to the game layout that would delete the songs form the Custom Levels folder?
A ton of the the folders' names are just some hashes that make it impossible to find a song that I'd like to delete (duplicate songs or simply songs I don't like).

**Comment by SynthwaveFox** [comment]
I remember there was a button for it, but now every time I look, it's gone.

**Comment by DeadlyKitten** [comment]
SongBrowser and Enhanced Search & Filters should both have this capability, iirc.

This has nothing to do with ModAssistant, which just installs mods.

**Comment by lolPants** [comment]
Like Steven said, this isn't in the scope of ModAssistant.
