### ISSUE TITLE
all mods gone and not showing up on mod assistant

### ISSUE THREAD

**Issue by IntenseGamerHD** [Assistant/ModAssistant#224]
I opened beat saber this morning and all of my mods were gone and ModAssistant just shows a blank page for where mods should be, i tried uninstalling and reinstalling it (which is the extent of my technical knowledge), is this just an update that broke it or is something wrong?
![image](https://user-images.githubusercontent.com/36389512/90424312-c5581880-e072-11ea-9c00-605ca15cda7b.png)
here is the log if that helps: https://p.teknik.io/43Two
(Im not sure if this is even the right place to post this)

**Comment by electroninja08** [comment]
thank god someone else has this issue

**Comment by electroninja08** [comment]
this needs attention

**Comment by Basti-Fantasti** [comment]
yep, same issue here. Mods show up for older versions when toggling game version but not for installed 1.11.0

**Comment by Tsavoryte** [comment]
i have this too, probably something server side but idk

**Comment by Melopod** [comment]
This is normal. Mods have not been updated to 1.11.0 yet. ModAssistant reflects this.

**Comment by IntenseGamerHD** [comment]
ah ok thanks, so if i play on the older version i could use mods?  just until its updated

**Comment by Melopod** [comment]
Once updated, older mods are no longer supported. It’s at your own risk.

**Comment by IntenseGamerHD** [comment]
ok, ill just wait, thanks for the help

**Comment by Tsavoryte** [comment]
sorry to comment after closing but just wanted to say attempting to patch 1.11.0 with 1.8 mods doesn't seem to work for the most part but songcore seems to be there.

**Comment by Melopod** [comment]
<1.11.0 mods will not work on version 1.11.0. Please just wait for the mods to be updated
