### ISSUE TITLE
[Question/Bug] Since new update, all songs are unplayable, and mod assistant is blank. 

### ISSUE THREAD

**Issue by mchety** [Assistant/ModAssistant#225]
Since the update for the Linkin Park song pack, all of my ost hand custom songs show up, but nothing happens when I click the play button. And then in mod assistant, the page for version 1.11.0 is blank:
![Annotation 2020-08-17 122227](https://user-images.githubusercontent.com/65556297/90430377-8f239480-e084-11ea-8f1b-9744772ab856.png)

But the page for version 1.8.0 shows all of the mods. Is this something to do with mod assistant, or is this just something else with the game?

**Comment by Melopod** [comment]
See issue #224

**Comment by 8BitCerberus** [comment]
Same issue for me as well. All my songs are still in /Beat Saber_Data/CustomLevels/ but not even showing up in-game, much less merely being unplayable. With previous updates that have killed mods until they were updated for the new version, at least the songs were still available to play. What's the deal with this new version?

There's a new subfolder in the Beat Saber install, "Old 1.10.0 Plugins" that contains all the plugins from before. Not as concerned about them though, I assume they'll get updated eventually. Main concern is the songs not being loaded or playable.

**Comment by DeadlyKitten** [comment]
Not a problem with Mod Assistant. After updates mods need time to be updated to be compatible. No mods are shown for 1.11.0 because at the time there were no mods on BeatMods.

As for songs, they should all still work; the base game takes much longer to load them without SongCore, you just have to be patient.

**Comment by mhombach** [comment]
@DeadlyKitten Can you close this issue as it is solved? :)

**Comment by lolPants** [comment]
ModAssistant showing no mods is due to there not being any mods, a more helpful display was added as of ca876354732ba286b0681b384506886fcbfbc128 and will be pushed in the next patch.
