### ISSUE TITLE
Cant cange Gamer version

### ISSUE THREAD

**Issue by llanelwy** [Assistant/ModAssistant#228]
Hi,

version 1.1.13

can no longer change the game version from the drop down it is greyed out and stuck on 1.11.1

thanks

Steve

**Comment by lolPants** [comment]
Going to need some more details on this. Steps to reproduce would be best.

**Comment by llanelwy** [comment]
When i submitted it you could not change the game version to an
older version from the current one. It is resolved though. it was when it
next updated
