### ISSUE TITLE
Infinite loading of Mods available.

### ISSUE THREAD

**Issue by RusJJ** [Assistant/ModAssistant#230]
I have an access to beatmods. Yes.

**Comment by OnSive** [comment]
?

**Comment by mhombach** [comment]
I think this issue can be closed, as it is clearly a troll.
@RusJJ  if you are serious about a bug request, stick to rules/formatting and give as much information about the problem as possible.

**Comment by RusJJ** [comment]
Ask me 2 months far, lol. The issue weirdly fixed just by updating BSIPA. 2 months ago.

**Comment by mhombach** [comment]
@RusJJ I know it's not easy, but you can actively support this software by closing issues that are not valid anymore. Otherwise, the devs and us will also use our rare free time to investigate issues that are not even existing anymore :)
