### ISSUE TITLE
After the first time I installed Mod Assistant, my Beat Saber gameplay went downhill, I literally cannot even play BS anymore because my framerate drops down to like 10 or lower and my screen will freeze from every 5 seconds, to every 10 seconds, to every 2 seconds. Why did MA do this to my pc?

### ISSUE THREAD

**Issue by JohnDelta1** [Assistant/ModAssistant#231]

**Comment by Futuremappermydud** [comment]
Bad pc

**Comment by Futuremappermydud** [comment]
Also you probably installed every mod

**Comment by MsFloofie** [comment]
Puts everything in the title instead of description. nice.

**Comment by mhombach** [comment]
I think this issue can be closed, as it is clearly a troll.
@JohnDelta1 if you are serious about a bug request, stick to rules/formatting and give as much information about the problem as possible.

**Comment by lolPants** [comment]
ModAssistant only installs mods you tell it to. Installing a large number of mods will slow your game down significantly, as each mod adds overhead. If you are still having problems I suggest visiting the #pc-help channel on the [Beat Saber Modding Discord](https://discord.gg/beatsabermods)
