### ISSUE TITLE
Installer not adding plugins to plugins folder

### ISSUE THREAD

**Issue by Nukeman52** [Assistant/ModAssistant#236]
Issue is as title says
Everything is done correctly except for the plugins folder
Plugins folder is created but nothing is added to the Plugins folder

**Comment by TraceyC77** [comment]
I've run into the same issue.

I had just uninstalled all mods and BSIPA because I wasn't seeing some mods in Beatsaber. Then I reinstalled BSIPA, launched ModAssistant and reinstalled my previous mods.

The only thing under the Plugins folder is the .cache folder.

**Comment by DeadlyKitten** [comment]
Plugins are installed to `IPA/Pending/Plugins`. They are moved to `Plugins` when the game is ran.

**Comment by lolPants** [comment]
Closing due to not being a bug
