### ISSUE TITLE
ModAssistant erroring out when new version of BeatSaber is available, but not installed.

### ISSUE THREAD

**Issue by EllyKida** [Assistant/ModAssistant#239]
I saw that BeatSaber got updated, but I didn't wanted to update to 1.12.1 because I don't want my mods to break. So I tried changing the manifest to trick steam that I still have the old version which worked. But ModAssistand wouldn't open anymore as can be seen in the error message screenshot..

![2020-10-13 21_55_47-Window](https://user-images.githubusercontent.com/38163161/95909883-82c76980-0d9f-11eb-9da8-b28ec5d8d97a.png)

At first I thought by changing the manifest I broke ModAssistant, 
so I checked the config => nothing wrong.
Changed the BeatSaber manifest back => Still error.
So I read the error message. Thanks to Opensource and great programming by the developers, I found out that the "Game Version:" ModAssistand shows is loading a JSON from "https://versions.beatmods.com/versions.json" and there the version "1.12.1" was already included.

I thought that "System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary" seems to try to compare something. And after I updated BeatSaber to version 1.12.1 ModAssisant started up without an error (Except a blank screen in the "Mods" tab when "1.12.1" is selected).

I guess it wants to forcefully use the new 1.12.1 value it's got in the JSON but couldn't find it on my system because I didn't update. Only after Updating to the said version it worked.

I hope I could explain myself well enough that it can be understood. 😅

Anyways, Thanks for making this great tool. Hopefully the issue is fixed someday.

**Comment by TheJmJ** [comment]
I managed to do a quick hot glue fix on this issue. This doesn't fix the issue completely, but only temporarily passes through the version it couldn't find without any error, and manages to catch the currently installed version.

In MainWindow.xaml.cs file, in the method CheckAliases, I wrapped the object[] aliasArray part in a if-check. It can be found on row 198.
Here's my changes from row 196 forwards, named object x and the added if-statement
`            foreach (string version in versions)
            {
                object x;
                if (Objects.TryGetValue(version, out x))
                {
                    object[] aliasArray = (object[])x;
                    foreach (object alias in aliasArray)
                    {
                        if (alias.ToString() == detectedVersion)
                        {
                            GameVersionOverride = detectedVersion;
                            return version;
                        }
                    }
                }
            }`

**Comment by TheJmJ** [comment]
I did a quick hotglue fix as seen above, and did a pull request https://github.com/Assistant/ModAssistant/pull/240
I couldn't completely understand the code in the quick glance I took in it, but that at least fixes the issue temporarily, or rather hides it under the rug.

**Comment by bavis-m** [comment]
The issue is that https://versions.beatmods.com/versions.json returns a `1.12.1` version, but https://alias.beatmods.com/aliases.json has no aliases for it. That's what it's trying to look up in the Dictionary (and failing to do)

**Comment by lolPants** [comment]
#240 should fix this going forwards
