### ISSUE TITLE
Version 1.1.0 missing mods

### ISSUE THREAD

**Issue by MarkoPoro** [Assistant/ModAssistant#24]
The custom song loader and leaderbord mods are missing in the 1.1.0 version. When do they come for this version?

**Comment by megalon** [comment]
This is not an issue with Mod Assistant. Mod Assistant simply pulls the latest approved mods from Beat Mods.
ScoreSaber is being updated and hasn't been uploaded yet to Beat Mods, and Song Loader is no longer required. See #23
