### ISSUE TITLE
Won't load the mods.

### ISSUE THREAD

**Issue by chilleryzz** [Assistant/ModAssistant#242]
Whenever it says it's done "loading the mods" it just shows nothing and I can't install any mods. I did just get the new version of BS with the new multiplayer thing, but something is probably wrong with this. Please help!

**Comment by DeadlyKitten** [comment]
The latest version has no mods uploaded to BeatMods yet, so none will appear in ModAssistant. You'll just have to be patient.

**Comment by chilleryzz** [comment]
Alright, thanks then!
