### ISSUE TITLE
Songcore wont load songs

### ISSUE THREAD

**Issue by determinedtree** [Assistant/ModAssistant#247]
I reverted beat saber to version 1.11.0 (i also tried 1.10.0 it didn't work either) after this most recent update. Now I have mods but when i click on a song to download it while in beat saber it just gives me a blank sorta screen, idk how to explain it. I can ss if needed. Just wondering if anyone knows how to fix this before I spend 3 hours figuring it out myself.

**Comment by lolPants** [comment]
Please leave your bug report in the correct repo, you will find the SongCore repo at https://github.com/Kylemc1413/SongCore

Please note it is unlikely that you will get very far as most people in the BSMG community don't support older game versions.
