### ISSUE TITLE
saying my legit copy is piratd and will not work

### ISSUE THREAD

**Issue by plkelley** [Assistant/ModAssistant#25]

**Comment by Kylemc1413** [comment]
Delete your Once pirated but now legit game folder entirely and then reinstall to remove the offending files leftover from when it was pirated

**Comment by plkelley** [comment]
done and done DRM is still active

**Comment by plkelley** [comment]
ftr the only copy i have and use is from steam

**Comment by Kylemc1413** [comment]
Then your version is either 
A. Actually pirated 
or
B. You didn't completely delete the folder and/or restart ModAssistant

**Comment by plkelley** [comment]
![image](https://user-images.githubusercontent.com/16781985/59400240-a150c700-8d4b-11e9-8f61-f41ec9a64e79.png)

A. Uninstalled and deleted the folder
B. Brand spanking new install from steam I guess steam is pirating the game and putting it on my pc

**Comment by Kylemc1413** [comment]
Can you screenshot the Beat Saber_Data/Managed folder?

**Comment by Kylemc1413** [comment]
Beat Saber_Data/Plugins* My bad

**Comment by plkelley** [comment]
![image](https://user-images.githubusercontent.com/16781985/59400355-05738b00-8d4c-11e9-9176-c62d065a3437.png)

**Comment by Kylemc1413** [comment]
Can you screenshot ModAssistant's full window and the path it's pointing to?

**Comment by plkelley** [comment]
I cant point mod assist, ive deleted it and re-downloaded it from git, it continues to give me the same message

**Comment by plkelley** [comment]
![image](https://user-images.githubusercontent.com/16781985/59400537-921e4900-8d4c-11e9-95f8-451af484cd74.png)

**Comment by Kylemc1413** [comment]
Is it possible you pirated the game to a different location on your computer in the past that it might be autodetecting as your installation instead of your steam library?

**Comment by plkelley** [comment]
![image](https://user-images.githubusercontent.com/16781985/59400634-fa6d2a80-8d4c-11e9-910b-ff2f174c72f7.png)

**Comment by plkelley** [comment]
pointed and still getting the same message
this is the only ver on my compy, I love your app so this is all we use here at home

**Comment by Kylemc1413** [comment]
The only way it would show that invalid window is if it detected pirated files in the path it's pointing to. Since your game folder is clearly clean of files, it is most likely pointing to a path elsewhere on your pc instead that contains those files, I recommend you look through anywhere on your pc someone else may have installed a pirated version of the game into in the past, and if you find such a folder, delete it

**Comment by plkelley** [comment]
ill do a grep, ty, after running your manager it works in game just fine just not the desktop app
