### ISSUE TITLE
"No Mods available for this version of Beat Saber"

### ISSUE THREAD

**Issue by LostGirl046** [Assistant/ModAssistant#252]
Hello, I've never used ModAssistant before and just got Beat Saber. I've started the game up a couple of times but the mods section in the ModAssistant says "No Mods available for this version of Beat Saber."

Does this mean I cannot download any custom songs in Beat Saber until we get an update to ModAssistant?
![ModAssistant](https://user-images.githubusercontent.com/31037354/96669992-62158b80-132c-11eb-97c7-c42a28dc1ee4.PNG)

**Comment by Melopod** [comment]
Custom Songs are *not* mods.
Custom Songs/Levels have been supported by the base game since 1.0 release (May 2019).
If you mean literally downloading the songs through the game while in vr, no, that requires a mod. Otherwise, Custom Songs still, and have always worked.
There are currently no mods available for the current game version, as the update has only just recently been released. That’s all the message means.

**Comment by LostGirl046** [comment]
Hi, thanks for the quick response.
Yes, I thought ModAssistant was a mod to help me be able to download/search for songs while in-game.
Sorry if I'm mistaken, or that's just one of the possibilities.
Sent from Yahoo Mail on Android 
 
  On Tue, Oct 20, 2020 at 11:36 PM, Melopod<notifications@github.com> wrote:   


Custom Songs are not mods.
Custom Songs/Levels have been supported by the base game since 1.0 release (May 2019).
If you mean literally downloading the songs through the game while in vr, no, that requires a mod. Otherwise, Custom Songs still, and have always worked.
There are currently no mods available for the current game version, as the update has only just recently been released. That’s all the message means.

**Comment by Melopod** [comment]
No, that would be the mod named BeatSaverDownloader. Mod Assistant simply allows you to download and install mods off of BeatMods hassle-free. It has no functionality for in game song downloading. It is not a mod, just a mod installer.

**Comment by LostGirl046** [comment]
Got it, thanks so much!

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 21, 2020 at 1:12 AM, Melopod<notifications@github.com> wrote:   


No, that would be the mod named BeatSaverDownloader. Mod Assistant simply allows you to download and install mods off of BeatMods hassle-free. It has no functionality for in game song downloading. It is not a mod, just a mod installer.
