### ISSUE TITLE
Still lists "No Mods available for this version of Beat Saber"

### ISSUE THREAD

**Issue by wonnov** [Assistant/ModAssistant#254]
I just installed this update1.1.15 yesterday.  Thank you, btw. 
It's still not loading any mods with the current version of the game installed. (see screenshot attached).
I do see mods if I select a different version of the game in the dropdown on the bottom left (see screenshot attached)
It seems like another minor update of the game may have come out right before I installed this. 1.12.2 is what I'm on.

Hope this helps.

![Screenshot 2020-10-21 080010](https://user-images.githubusercontent.com/61562520/96716967-ca3b9000-1373-11eb-8de3-f233d7d644ff.jpg)
![Screenshot 2020-10-21 080140](https://user-images.githubusercontent.com/61562520/96716969-ca3b9000-1373-11eb-8289-cb79e18a59d8.jpg)

**Comment by lolPants** [comment]
ModAssistant says there are no mods available because there are currently no mods available.
