### ISSUE TITLE
IPA config folder not allowing plugins past pending stage in the file.

### ISSUE THREAD

**Issue by Rickers2004** [Assistant/ModAssistant#258]
plugins folder remains empty after Mod download.

**Comment by Parapass** [comment]
Did you launch the game after, and if so, did the plugins load or not load?

**Comment by Rickers2004** [comment]
When the game launched, none of the plugins or the mod tab loaded.

**Comment by Rickers2004** [comment]
after launching the game several times, the mods loaded.

**Comment by MarcDelp** [comment]
For others like me for which launching the game multiple time didn't changed anything, I followed what https://github.com/Assistant/ModAssistant/issues/260#issuecomment-716173407 said.

In my case : run the IPA.exe file in command prompt, then launched BeatSaber, quit the game, run ModAssistant, reinstall mods, start game again and mods were back! Hope this help some people.

**Comment by SeiferLeonheart** [comment]
> For others like me for which launching the game multiple time didn't changed anything, I followed what [#260 (comment)](https://github.com/Assistant/ModAssistant/issues/260#issuecomment-716173407) said.
> 
> In my case : run the IPA.exe file in command prompt, then launched BeatSaber, quit the game, run ModAssistant, reinstall mods, start game again and mods were back! Hope this help some people.

Had the exact same issue today and these steps still worked, thanks!. For the record this was the first google result for "beat saber mods going to pending folder" (at least for me) so commenting to thank you and to reinforce that still works.

**Comment by breegus** [comment]
> For others like me for which launching the game multiple time didn't changed anything, I followed what [#260 (comment)](https://github.com/bsmg/ModAssistant/issues/260#issuecomment-716173407) said.
> 
> In my case : run the IPA.exe file in command prompt, then launched BeatSaber, quit the game, run ModAssistant, reinstall mods, start game again and mods were back! Hope this help some people.

Five years later and you just fixed my game! Thank you :)
