### ISSUE TITLE
Continuous graphics driver crashes

### ISSUE THREAD

**Issue by Sellorio** [Assistant/ModAssistant#259]
Start the app and my graphics driver continuously crashes until I close it.

Not sure why you're doing anything that would cause this but please stop :P

**Comment by lolPants** [comment]
ModAssistant is just a standard XAML app, nothing comes to mind that would cause this. Gonna need some logs or some method to repro in order to investigate.

**Comment by Sellorio** [comment]
Ah fair, I'll see what I can find RE WPF apps causing gfx crashes.

**Comment by Sellorio** [comment]
Updating drivers solved this. Presumably something in the drivers was broken or corrupted. I usually stay 1 version behind so I can update when things like this break.... what a world to live in.
