### ISSUE TITLE
Song Browser Missing?

### ISSUE THREAD

**Issue by tooleo** [Assistant/ModAssistant#26]
Everything with the ModAssistant is amazing except one small thing. I've been waiting to see if the Song Browser mod was going to be added (mod that lets you sort through playlists by various fields). I'm not sure if this is an issue on my end or what. I have noticed after the update that there is a random button added and there is some basic search functionality. I assumed this was something added in the core game since the bulk of the functionality from the song browser mod was missing. Am I just being dumb and it is there? 

I was going to wait to ask on here but i saw that the song browser mod was working with the current version of the game and figured I would ask and see. If I'm being a pest I apologies. Again thank you so much for getting the ModAssistant up and running so fast after the update. everyone involved is awesome and the community loves you guys.... even if there are some people out there that only know how to complain. Thanks a ton!

**Comment by Assistant** [comment]
I'm not sure what the state of SongBrowser is, but Mod Assistant simply downloads and installs what's available on BeatMods.
I suggest going to the #support channel in [BSMG](https://discord.gg/beatsabermods) to see if there's something wrong with your setup, or if there really is a bug on SongBrowser you should report it on its github page. If you select a mod and click the `Mod Info` button next to the `Install` button, it'll take you to the mod's info page, which usually is its github page.

**Comment by tooleo** [comment]
Guess I should have waited one more day. I just got home from work and checked the Mod Assistant and song browser is on there now. Thanks a ton!
