### ISSUE TITLE
Anti Virus Flags Up Modassistant.exe 

### ISSUE THREAD

**Issue by Jakeonator03** [Assistant/ModAssistant#263]
My anti virus (Bullguard) flags up mod assistant as a threat. I know its not a threat, yet others may not see it that way.

Suspected file: ModAssistant.exe

Path: E:\Mod Assistant\ModAssistant.exe

Details
•    Drop.Win32.MLDExe.4480

Files modified
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\hyjdhynw.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\hyjdhynw.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\hyjdhynw.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\s5we0fkn.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\s5we0fkn.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\s5we0fkn.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\aptj023s.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\aptj023s.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\aptj023s.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\qpt1qley.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\qpt1qley.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\qpt1qley.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\pmrhnqtw.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\pmrhnqtw.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\pmrhnqtw.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\kgtu0ncn.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\kgtu0ncn.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\kgtu0ncn.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\2v3pua3h.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\2v3pua3h.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\2v3pua3h.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\hoglempu.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\hoglempu.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\hoglempu.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\ixugm1qr.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\ixugm1qr.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\ixugm1qr.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\srslhdep.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\srslhdep.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\srslhdep.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\ghoczouw.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\ghoczouw.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.16.0\ghoczouw.tmp
•    E:\Mod Assistant\ModAssistant.exe
•    E:\Mod Assistant\ModAssistant.exe
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\enzn4pgo.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\enzn4pgo.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\enzn4pgo.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\cq35yjqt.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\cq35yjqt.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\cq35yjqt.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\uycqez1d.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\uycqez1d.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\uycqez1d.tmp
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\icalcnww.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\icalcnww.newcfg
•    C:\Users\jakec\AppData\Local\ModAssistant\ModAssistant.exe_Url_laqie0f5uek041youckp4slcdrio5lg1\1.1.15.0\icalcnww.tmp
•    E:\Mod Assistant\ModAssistant.exe

Processes
•    [10180] E:\Mod Assistant\ModAssistant.exe
•    [9052] E:\Mod Assistant\ModAssistant.exe

25/10/2020 10:47:52

**Comment by ImSapphire** [comment]
Add exceptions for ModAssistant in your antivirus. As far as I know, Bullguard isn't a common antivirus.
