### ISSUE TITLE
Mods seem to be being checked/unchecked randomly/nonsensically?

### ISSUE THREAD

**Issue by Jhenox** [Assistant/ModAssistant#267]
I check ModAssistant at least once a day. When I open it, there are always checked mods on the left but there doesn't seem to be any sense to it. There are checked mods that I have installed but don't need an update and checked mods I don't have installed that are unintentionally installed if I click Install or Update. It would be nice that the only items that are prechecked are ones that are installed and need an update. Thank you.

**Comment by megalon** [comment]
I see this is an old post but I'll comment here to explain how the checklist works.

Mod Assistant saves which mods you have checked, but the next time you launch Mod Assistant, it will always check mods on this list of default mods. I can't say I agree with this, but it's how it works right now.
https://github.com/Assistant/ModAssistant/blob/76432df7fe3cc2142da29f3aaaf5603be8d661cd/ModAssistant/Pages/Mods.xaml.cs#L27

Mods that are required for other mods to function properly (known as dependencies in MA) are also checked, but shown with the disabled checkbox.

Mod Assistant does not uncheck mods that are already installed and up to date. However, you can set whether or not you want to reinstall them using the "Reinstall Installed Mods" option in the Settings menu.

And finally, Mod Assistant will not install a mod if you have a _newer_ version already installed, even if it is checked in the list.
