### ISSUE TITLE
Custom Sabers not showing up after following directions and reinstalling 

### ISSUE THREAD

**Issue by Shimarra** [Assistant/ModAssistant#270]
I'm on Rift S using Occulus software and I've followed the directions exactly to the T 3 times including a full uninstall of beatsaber and I get the custom songs options but no custom sabers. I'm really confused as to why. I downloaded the saber mod .zip and placed the folders inside the game folder (plugins and customs sabers). Any ideas?

**Comment by Parapass** [comment]
Do you mean on ModAssistant Custom Sabers does not show up or something else?

**Comment by lolPants** [comment]
The `#pc-help` channel on the [BSMG Discord](https://discord.gg/beatsabermods) will be able to troubleshoot your issue.
