### ISSUE TITLE
so i couldnt tell if this was already here or not so i'll ask now

### ISSUE THREAD

**Issue by R4LS3I** [Assistant/ModAssistant#271]
i went to go install it and it cant detect my directory and i can go to install it but I don't know where I am supposed to put it because it wont let me put it on my oculus at all, I there's no folders or anything for me to even put it on it its just blank. So i would really appreciate some help, thanks in advance

**Comment by lolPants** [comment]
The `#pc-help` channel on the [BSMG Discord](https://discord.gg/beatsabermods) will be able to troubleshoot your issue.
