### ISSUE TITLE
Cannot find the custom tabs in Beatsaber

### ISSUE THREAD

**Issue by C4lidas** [Assistant/ModAssistant#275]
I don't know why but I cannot seem to find the custom tab or even the mods tab in BeatSaber at all. I have tried reinstalling BeatSaber and the modpack but none of it fixes, anyone know anything?

**Comment by lolPants** [comment]
The `#pc-help` channel on the [BSMG Discord](https://discord.gg/beatsabermods) will be able to troubleshoot your issue.
