### ISSUE TITLE
Not able to download in game song

### ISSUE THREAD

**Issue by SpongBob128** [Assistant/ModAssistant#277]
mod runs fine the only thing is the custom songs arent able to download when you click them its just black not letting you look at them or search them

**Comment by mcgic005** [comment]
Hi SpongBob128,

Not  a direct soluition to the issue, however I myself download the songs offline on bsaber, look at this page for more info: [](https://bsaber.com/beatsync/)

I hope this helps.

Best wishes

**Comment by Parapass** [comment]
BeatSaver is currently down. 
![image](https://user-images.githubusercontent.com/59424861/99955788-eb1c4a00-2d52-11eb-82f2-b2527226d4a7.png)

**Comment by username19955** [comment]
Does anybody know if this has been fixed?

**Comment by username19955** [comment]
> BeatSaver is currently down.
> ![image](https://user-images.githubusercontent.com/59424861/99955788-eb1c4a00-2d52-11eb-82f2-b2527226d4a7.png)

Where did you find that info that the servers are down or whatever?

**Comment by lolPants** [comment]
@username19955 https://discord.gg/beatsabermods

**Comment by lolPants** [comment]
Closing this due to not being an issue with ModAssistant
