### ISSUE TITLE
Beatsaver ratelimit not working correctly

### ISSUE THREAD

**Issue by PulseLane** [Assistant/ModAssistant#284]
One issue is that the time displayed on the status always lists the time in UTC, regardless of the current system time. Another issue is that it seems to wait indefinitely, or at least *far* longer than it needs to, and certainly past the time it displays.

**Comment by Patryn43** [comment]
I am having the same issue. It makes installing larger playlists impossible. 
![ratelimit](https://user-images.githubusercontent.com/28033247/107989072-089a3200-6f97-11eb-8088-ba1e786517d5.PNG)

**Comment by livejamie** [comment]
I seem to still be getting this bug, running 1.1.18

![image](https://user-images.githubusercontent.com/49513/116989997-5dd90c00-ac87-11eb-9cf4-6fa6254351af.png)

It's 3:18 right now and it's displaying hat it will resume at 10:15, not sure what that means?
