### ISSUE TITLE
Feature: Linux Support

### ISSUE THREAD

**Issue by BBKolton** [Assistant/ModAssistant#285]
For those of us who'd love to drop Windows 10. I'm personally running Ubuntu 20 LTS

**Comment by dllu** [comment]
Same, I'm playing Beat Saber on Arch Linux. It seems the mod assistant crashes in Proton.

![2021-02-16-19:32:56:736808639-maim](https://user-images.githubusercontent.com/14482624/108152422-e0d9c580-708d-11eb-95d3-d8ac9a53f506.png)

**Comment by Vinjul1704** [comment]
+1 for Linux support.

**Comment by lolPants** [comment]
ModAssistant is unlikely to be ported to Linux for the reasons outlined in #357.
