### ISSUE TITLE
cannot search songs in game anymore and 1 click installs fail everytime

### ISSUE THREAD

**Issue by MrfadedPhantom** [Assistant/ModAssistant#286]
every song i search results in a blank screen even old songs i used to play no longer show up so i tryed installing from beast saber .com and that also just shows a fail screen, even manual install button give me a dead links, so is this mod just dead now?

**Comment by ConnerPartaker** [comment]
I've been trying to figure this out too. Finally joined the discord as a last ditch effort, it seems recently there's been BeatSaver API abuse, so they temporarily disabled the download feature until they find a fix.

**Comment by MrfadedPhantom** [comment]
Damn :( where do I join the discord?

**Comment by MeuhMeuh** [comment]
Same here :(

**Comment by Parapass** [comment]
discord.gg/beatsabermods
