### ISSUE TITLE
ModAssistant exception System.IO.IOException

### ISSUE THREAD

**Issue by mishtr0n** [Assistant/ModAssistant#288]
Title. I had previously installed MA and it worked, even loaded some mods up. However I went to launch up Beat Saber today and found that MA didn't exist anymore on my computer so I redownloaded it and I was presented with this. 
![image](https://user-images.githubusercontent.com/76872435/103458207-215fc880-4d06-11eb-8e0f-30acc14f1a79.png)

**Comment by TigerTJJ** [comment]
![image](https://user-images.githubusercontent.com/17763198/103468383-83c8c100-4d26-11eb-848e-405ef737045d.png)
I have something similar. IO Exception, but the file was not found

**Comment by bahdvp** [comment]
I unchecked scoresaver, and some of the other unnecessary mods from the default modassistant install and it worked. Not sure which one was the culprit but give that a go.

**Comment by lolPants** [comment]
Gonna need some reproduction steps before I can begin to solve this

**Comment by bahdvp** [comment]
For me, it was simply:

1) Install fresh copy of beat saber
2) Download modassistant
3) Click install with default settings.

I don't think this is an issue with modassistant. More likely an issue with one of the mods that may or may not have been fixed already.

**Comment by lolPants** [comment]
Closing due to inability to reproduce and inactivity.
