### ISSUE TITLE
Not selecting Beat Saber folder

### ISSUE THREAD

**Issue by NoC1u3z** [Assistant/ModAssistant#290]
Every time I click on my Beat Saber folder it will open it not select it, I've tried right clicking and opening folder manually.

**Comment by NoC1u3z** [comment]
I am very dumb I have fixed this.

**Comment by bruh528289191** [comment]
please tell me what you did because im dying trying to figure it out

**Comment by bruh528289191** [comment]
never mind just fucked around and figured it out

**Comment by MagicTurtle23** [comment]
I need help because I don't know what the f*ck i'm doing.

**Comment by lolPants** [comment]
Gonna close this and direct you to the [BSMG Discord](https://discord.gg/beatsabermods) `#pc-help` channel, they should be able assist.
