### ISSUE TITLE
Beatsaber Update- can't run any song whatsoever

### ISSUE THREAD

**Issue by Noelliphant** [Assistant/ModAssistant#297]
Beatsaber updated a few hours ago, and upon loading songs, the screen blacks out and shows me my zone outline only. I'm on Oculus rift S and Beatsaber version 1.13.2. I can't pause and exit the song, I have to close the game and reboot. I've tried songs on the regular game, songs I downloaded on BeastSaver, and I tried turning off mods. maybe I need a new update for Mod Assistant, but regardless, its upsetting. please help!

**Comment by littlenancy1** [comment]
I'm having the same problem. I'm on Vive and Steam VR and Beatsaber 1.13.2 version.

**Comment by ImSapphire** [comment]
Try going into Mod Assistant > Options and selecting Uninstall BSIPA. Since the game updated, mods are now broken.

**Comment by littlenancy1** [comment]
Thank you

On Thursday, January 21, 2021 Sapphire <reply@reply.github.com> wrote:



Try going into Mod Assistant > Options and selecting Uninstall BSIPA. Since the game updated, mods are now broken.

**Comment by Noelliphant** [comment]
Thank you so much!
