### ISSUE TITLE
Mod Assistant broke my beat saber.

### ISSUE THREAD

**Issue by JennySkittle** [Assistant/ModAssistant#299]
I was following a youtube tutorial on how to get custom sabers [https://youtu.be/K9Rlv-nu75Y](url) and following the tutorial completely broke my beat saber. It wont open and it just loads indefinitely. I am on the oculus home and not steam but i just thought id change the file location in settings and everything will be fine. thats not the case. please help. we can take as much time as you need

**Comment by JennySkittle** [comment]
It just had to uninstall and install it a million times and it finally works.

**Comment by Parapass** [comment]
btw dont follow darkswitchpro tutorials, and if you want the custom sabers mod instead of saberfactory, go here: https://twitter.com/nalulululuna/status/1352701370944524289
