### ISSUE TITLE
Unhandled exception when BeatMods website is unreachable

### ISSUE THREAD

**Issue by Shadnix-was-taken** [Assistant/ModAssistant#3]
Tested with v.1.0.7

There is an unhandled exception when changing to the Mods tab while the BeatMods website is unreachable and returning HTTP error 502, which causes the application to crash. Any other HTTP error code might have the same result.

It would probably be better to catch that exception and inform the user, that the application was not able to reach the BeatMods website. Maybe even including the returned HTTP error code or any other error returned by the HttpWebRequest library.

Screenshot with the error message attached: 

![2019-05-15 22_44_27-Mod Assistant](https://user-images.githubusercontent.com/42559603/57808339-6c108380-7763-11e9-93d1-f0b5b9e5f075.png)

My local system language is German. Second and third line should translate to:

"System.Net.WebException: The remote server returned an error: (502) Invalid Gateway."

**Comment by Shadnix-was-taken** [comment]
I guess this got fixed in commit d3b97d0850cc8feccbdbe54e3cb2b00458f585c0 for release v1.0.8 and later?

btw - Thanks for your work.

**Comment by Assistant** [comment]
I wouldn't say it's entirely fixed, but it's somewhat fixed.
If BeatMods is down when you run the application it won't crash, but if it's down when you try to load mods it'll still crash. I'm not entirely sure how to handle that gracefully.

**Comment by raftario** [comment]
I fixed that in the old installer, I'll give a look at it.
