### ISSUE TITLE
OneClick Exception from BeatSaver - v1.0.23

### ISSUE THREAD

**Issue by xhuytox** [Assistant/ModAssistant#30]
![image](https://user-images.githubusercontent.com/20061642/60903006-6eec9980-a225-11e9-8324-4f13eaea65db.png)

**Comment by Assistant** [comment]
As the message suggests, it couldn't get the map details. 

Could you post which beatmap that happens with?

**Comment by sh-akira** [comment]
I found same issue with this map:
https://beatsaver.com/beatmap/3b0a

I don't know before but maybe JSON format on the beatsaver side has changed(at characteristics).
https://beatsaver.com/api/maps/detail/3b0a

**Comment by Assistant** [comment]
Looks like you're right, the API response changed in lolPants/beatsaver-reloaded@751d8b74aaf1b39884127929cbe5f867d29fe6ca

There's nothing I can do right now but I'll fix it when I get a chance.

**Comment by xhuytox** [comment]
Yeah, this is happening for every map so the API response change makes sense. Thanks for the update.

**Comment by fuji97** [comment]
I've updated the models in #31 and tested it, now works.

**Comment by xhuytox** [comment]
Can confirm that as of v1.0.24, OneClick is now working.
