### ISSUE TITLE
Update mod assistan

### ISSUE THREAD

**Issue by Bullerman1234** [Assistant/ModAssistant#307]
Hi i just saw the new update from beat saber. 1.13.4 and theres no mod in that version in mod assistan. Can someone pls help me if that is a bug or it just need to be updateted.

**Comment by kakyoinjoestar** [comment]
> Hi i just saw the new update from beat saber. 1.13.4 and theres no mod in that version in mod assistan. Can someone pls help me if that is a bug or it just need to be updateted.

i have the same problem 
i hope there is a new update for it soon

**Comment by MarvinS97** [comment]
Can confirm, mods don't work anymore.

**Comment by DeadlyKitten** [comment]
👏 Mod 👏 Assistant 👏 has 👏 nothing 👏 to 👏 do 👏 with 👏 the 👏 mods 👏

**Comment by Melopod** [comment]
No, as MA will only list updated and approved mods that are listed on BeatMods. No mods (obviously) have yet been updated or approved for the newest BS version, hence an empty list. 
This is actually listed in the readme, believe it or not.
MA has nothing to do with the mods, as the comment above yours states. (and this kind of comment is added nonstop to this GtiHub, despite MA having absolutely nothing to do with the mods, hence the attitude)

**Comment by DeadlyKitten** [comment]
Mod Assistant retrieves the list of mods from BeatMods. The version of Mod Assistant makes no difference, any version of Mod Assistant can install mods for any version of Beat Saber. That being said, if there are no mods listed for the current version of the game, then that is because there are no mods to download for that version. You'll have to be patient and wait for mod developers to update their mods to work on the latest version.

**Comment by ThatGuyOnCops** [comment]
Appreciate the well informed responses yall. Really appreciate the professionalism. I understand how the same comment and stuff can get old (As a streamer). Thank you guys. Hopefully that this will keep people from asking more in the future <3

**Comment by Melopod** [comment]
Thanks for the well wished. And unfortunately no lmao. Someone will just open up yet another issue without reading up on any of these, or the readme. Such is the pain of maintaining mods.

**Comment by Ashmain1** [comment]
how long does it usually take 
I'm new to this

**Comment by MtnFranke** [comment]
The essential mods to play custom songs again were updated yesterday.

**Comment by Jorvalt** [comment]
> No, as MA will only list updated and approved mods that are listed on BeatMods. No mods (obviously) have yet been updated or approved for the newest BS version, hence an empty list.
> This is actually listed in the readme, believe it or not.
> MA has nothing to do with the mods, as the comment above yours states. (and this kind of comment is added nonstop to this GtiHub, despite MA having absolutely nothing to do with the mods, hence the attitude)

It's still listing a bunch of mods though, and none of them work. If they weren't working for the current version, shouldn't the list be empty as you said?

**Comment by Melopod** [comment]
Sounds like it's due to the fact that since that reply was posted (check the date), mods have been uploaded.
Magic

**Comment by Jorvalt** [comment]
As I said, the mods still don't work.
If in fact ALL of these mods were supposedly updated to the latest game version yet still aren't working, that's a pretty big coincidence.
It seems more likely that ModAssistant is incorrectly displaying out of date mods, which would be an actual issue.

**Comment by Melopod** [comment]
Some game versions have minimal code changes or none at all that don't affect mods. Such as this latest jump between 1.13.4 to 1.13.5. The mods in MA are up to date and fine on either game version. If they aren't working for you that's a personal issue on your PC on your end. The troubleshooting guides on the wiki and the support channels in the BSMG Discord exist for this reason.

**Comment by Jorvalt** [comment]
This was working until the latest update.
Is the current version 1.13.5? MA is only showing up to 1.13.4

**Comment by Melopod** [comment]
> If they aren't working for you that's a personal issue on your PC on your end. The troubleshooting guides on the wiki and the support channels in the BSMG Discord exist for this reason.

**Comment by lolPants** [comment]
Leaving this open for now to allow for visibility, but locking due to this not being an actual issue with ModAssistant. If you need support with mods, read the above comment.
