### ISSUE TITLE
Feature: List selected but unavailable mods

### ISSUE THREAD

**Issue by YoukaiTheGit** [Assistant/ModAssistant#309]
Request: Show mods that are selected & saved with the "save selected mods" option, even if they are not available for the current/selected version of Beat Saber.

Reasons:
1) After a Beat Saber update, when waiting for mods to get updated: The mods are often posted on the BSMG discord a day or two before they appear in Mod Assistant.  In that case, it is useful to be reminded of which mods had been installed, to know which ones to go grab from Discord.
2) If the user has disabled Beat Saber updates, and wants to wait for certain mods to get updated before updating Beat Saber, then being able to see the current & not-yet-available mods in the same list (for the new BS version) is convenient.

**Comment by jemand771** [comment]
possible duplicate of #265

**Comment by YoukaiTheGit** [comment]
Agree, this is the same request as #265
