### ISSUE TITLE
Beat together 

### ISSUE THREAD

**Issue by caboose098** [Assistant/ModAssistant#316]
Since the recent update custom songs no longer show up when trying to play multiplayer on beat together. The same thing is happing with my friend and neither of us can see any lobbies that have custom songs playing.

**Comment by caboose098** [comment]
And sorry if this is the wrong place to ask for help but I wasn't really sure

**Comment by Melopod** [comment]
Mod Assistant only helps you install mods. It has nothing to do with mods themselves.

**Comment by caboose098** [comment]
Sorry I wasn't 100% sure and now I feel a bit silly but thanks for the quick answer
