### ISSUE TITLE
One-click install fails for iDOLM@STER Soundtrack Volume 1

### ISSUE THREAD

**Issue by Stevoisiak** [Assistant/ModAssistant#317]
**Issue**

Attempting to install the [iDOLM@STER Soundtrack Volume 1](https://bsaber.com/?s=iDOLM%40STER+Soundtrack+Volume+1+&orderby=relevance&order=DESC&post_type=post%2Cpage%2Cattachment%2Creplica_section%2Cvc4_templates) playlist with one-click install results in a FileNotFoundException saying the playlist file can't be found.

**Specifications**

- Windows 10
- ModAssistant 1.1.17
- Beat Saber 1.14.0

![Error message](https://user-images.githubusercontent.com/1330770/111948911-33a40400-8ab6-11eb-83cd-2452546857b2.png)

**Comment by Stevoisiak** [comment]
Why was this issue closed?

**Comment by DeadlyKitten** [comment]
Because it was fixed in [this commit](https://github.com/Assistant/ModAssistant/commit/b9e58c0b8c020985d284b31c14aae60c18912173).
