### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by Johnnyboy5498** [Assistant/ModAssistant#319]
So I have fully moved to Microsoft Edge and it says that ModAssistant.exe was blocked because it could harm your device.  I tried it on Google Chrome as well and it just installs, must be a Smart Shield thing. Being windows there is always a way around these types of things and I have it successfully installed, but I just thought you guys should know.

**Comment by programmer2514** [comment]
AFAIK you can't really avoid this - it's similar to the warning you get downloading an APK on Android

**Comment by dannypas00** [comment]
This always happens when trying to install an app downloaded from the internet that not many people have installed on windows before.
The only real solution for this is to have more people install the app beforehand.
