### ISSUE TITLE
Mods stop working after booting Beat Saber a second time

### ISSUE THREAD

**Issue by AndrewVCoding** [Assistant/ModAssistant#32]
Mods were working great for a little while after I first installed ModAssistant. I followed the instructions, launching Beat Saber without mods first, and then installing them. During this time, I opened and closed the game several times. After a couple of hours, I launched the game again to find there was no mod button in the menu anymore. I uninstalled the game and mods and repeated the whole installation process: launch without mods, close game, install mods. launch again, mods are there, close game, relaunch game, mods are no longer working. I've tried deleting game files, using other mod managers, uninstalling all mods except the required ones. But the mod button in the menu always disappears when I boot the game a second time after installing the mods. During this time, there were no updates to the game.

**Comment by Assistant** [comment]
Mod Assistant simply installs the mod files, it's not responsible in any way for their operation.
