### ISSUE TITLE
BSIPA error

### ISSUE THREAD

**Issue by Dennis644** [Assistant/ModAssistant#320]
whenever i install the BSIPA it inverts all the songs, and it causes an error in campaign song 17b it gives me a blue sword but the squares are red, anything i can do about this?

**Comment by Melopod** [comment]
Check the date

**Comment by Dennis644** [comment]
How do i do that? And how does that fix it?

**Comment by Melopod** [comment]
What? As in check what date it is today on the calendar. Anywhere. At this point the day's over already so it no longer applies.

**Comment by Dennis644** [comment]
Look my guy i come here for help, im asking because i dont know this shit, how about instead of being a dick you explain to me what i asked or what youre talking about

**Comment by DeadlyKitten** [comment]
April 1st is commonly known as April Fools Day. What you're describing was intentional behavior caused by a mod, but only on April 1st.

**Comment by Dennis644** [comment]
Thank you, where im from we dont celebrate this day, so it didnt cross my mind whatsoever
