### ISSUE TITLE
Not sure if this is a glitch or not

### ISSUE THREAD

**Issue by LePotatoMan** [Assistant/ModAssistant#321]
I can't play choose beat saber version 1.13.5 not sure if you are still working on this or not but i cannot choose this version especially because custom saber's don't work.

**Comment by lolPants** [comment]
ModAssistant uses version aliases to merge Beat Saber versions together that had no compatibility issues. Selecting `1.13.4` will list mods compatible with any Beat Saber version up to the next version in the list (at the time of writing, that means the latest available Beat Saber version).
