### ISSUE TITLE
pc saying that its a virus?

### ISSUE THREAD

**Issue by epicOswald123** [Assistant/ModAssistant#323]
it dosent say directly its a virus but it says it could be fishy, what do i do and is it safe?`

**Comment by lolPants** [comment]
Windows flags up unsigned `.exe`s as suspicious as they could have been made by anyone. However a signing key costs a lot of money (can be up to hundreds of dollars a year) so ModAssistant will remain unsigned. You can run the `.exe` through a [Virus Scan](https://www.virustotal.com/gui/url/697aedd6ee3bca29be9e5fb3d131fe104191df0420ddf097effd124386cc9f9d/detection), or manually audit the source code and build your own copy. Other than that you'll just have to take our word on the legitimacy of the application.
