### ISSUE TITLE
New to this and have a question

### ISSUE THREAD

**Issue by JCHB322** [Assistant/ModAssistant#327]
More a question than an issue... I know that Mod Assistant and Beat Saber need to be on the same game version... so I was just wondering since 1.13.5 seems to have been a minor fix update to the game, will the current Mod Assistant version 1.13.4 still work, or do I wait until MA has also been updated to 1.13.5 too? Just want to check before getting everything installed.

**Comment by Rayn322** [comment]
The 1.13.4 mods will work on 1.13.5 as well as 1.14.0

**Comment by JCHB322** [comment]
Thank you!
