### ISSUE TITLE
1.15.0 support please 

### ISSUE THREAD

**Issue by RaidenNo** [Assistant/ModAssistant#328]
So I forgot to turn off auto update on my beatsaber for oculus rift so my game updated to 1.15.0 and all my mods got ruined and when i try and launch beatsaber it's just a black screen because mod assistant doesn't support it yet so currently right now i am stuck with a beatsaber that doesn't work :(  also i can't downgrade versions because I'm on oculus).

**Comment by Melopod** [comment]
All mods on mod assistant have been tested and with fine with the current exception of enhancements

**Comment by lolPants** [comment]
Beat Saber version 1.15 has now been aliased on BeatMods, so ModAssistant should now recognise it.
