### ISSUE TITLE
Plugins not installed

### ISSUE THREAD

**Issue by Drosaca** [Assistant/ModAssistant#329]
plugins directory is created but stays empty
![image](https://user-images.githubusercontent.com/36480154/116795271-12cac780-aad4-11eb-80cc-a7c121802d9f.png)
![image](https://user-images.githubusercontent.com/36480154/116795278-2413d400-aad4-11eb-9282-14f7a686fd43.png)

**Comment by lolPants** [comment]
ModAssistant installs plugins to the BSIPA Pending directory, which will be loaded and moved to the `Plugins` directory when the game is started. If running the game still fails to load your plugins, I suggest asking for help in the `#pc-mods` channel on the [BSMG Discord](https://discord.gg/beatsabermods)

**Comment by carlbennett** [comment]
I had a similar issue which was resolved by following the [Clean Installation](https://bsmg.wiki/support/#clean-installation) instructions. Hope this helps anyone landing here from a web search.
