### ISSUE TITLE
Major Frames Drop

### ISSUE THREAD

**Issue by ZCIGUESS** [Assistant/ModAssistant#330]
So I had a run-in with another glitch in the newest version which crashes my game, so I switched to 1.1.16 and now when I run Beat Saber I get about 4 Frames per second. Any answers?

**Comment by lolPants** [comment]
This is not a direct issue with ModAssistant, this sounds like an issue with one of the mods you have installed. I suggest asking for help in the `#pc-mods` channel on the [BSMG Discord](https://discord.gg/beatsabermods).
