### ISSUE TITLE
Can't find option to add new songs

### ISSUE THREAD

**Issue by summerjase** [Assistant/ModAssistant#34]
Used to use the Beat Saver mod, but after an update there was no longer an option to add songs. Switched over to the recommended "Beat Assistant" hoping that would fix the issue and there still isn't an option. I am aware that it used to be an option under "mods" in the bottom bar of the game, but that's not even there anymore. Does this mean I have to manually download them from the internet to put them in? I thought the whole point of the 'assistant' was it was easier to use and what not. Would like to get an answer on how to add new songs in-game.

**Comment by Assistant** [comment]
The BeatSaver Downloader mod still exists and works. It sounds to me like you're having trouble with improperly installed mods, not with Mod Assistant.
Take a look at the support section of the wiki, and specifically [this part](https://bsmg.wiki/support#clean-installation) should fix most issues.
