### ISSUE TITLE
Custom songs don't show up in beat together

### ISSUE THREAD

**Issue by shpela** [Assistant/ModAssistant#340]
Hello,

It appears that the tab for custoim songs no longer shows up when you  create a Beat together server.
Me and my friends have the same issue. It stopped working about a week ago,

Is this a bug we can fix ourselves or does it need a  @patch?

**Comment by lolPants** [comment]
This is not a ModAssistant issue. I suggest opening a bug report on the BeatTogether repo(s).
https://github.com/pythonology/BeatTogether
https://github.com/pythonology/BeatTogether.Quest
