### ISSUE TITLE
Version 1.1.19 detected by Windows Defender as a Trojan

### ISSUE THREAD

**Issue by xephgobrr** [Assistant/ModAssistant#341]
New 1.1.19 is a virus???

**Comment by shrek-uberr** [comment]
can vouch; have to edit registry in order to complete the download
![image](https://user-images.githubusercontent.com/82292471/118052635-13bfec80-b351-11eb-97aa-83dd8a4847c4.png)
the auto update from a previous version just caused this to get autodeleted + its shortcut, probably also from antivirus

**Comment by xephgobrr** [comment]
How do I change the registry so I can download it ?

**Comment by shrek-uberr** [comment]
havent tried it myself but im assuming this will work (second set of instructions) https://support.microsoft.com/en-us/topic/information-about-the-attachment-manager-in-microsoft-windows-c48a4dcd-8de5-2af5-ee9b-cd795ae42738

**Comment by lolPants** [comment]
Version 1.1.19 has been yanked for now to prevent more people getting into a panic. As of now we are unsure why ModAssistant is being flagged as a virus by Windows Defender, but we're working on it.

There's not much more to say other than ModAssistant's code is publicly auditable if you're unsure on the legitimacy of the application. All releases can also be manually inspected using a tool such as dnSpy.

**Comment by lolPants** [comment]
I'm gonna leave this issue open for now in case anyone else who autoupdated before the release was yanked has questions and finds their way here.

**Comment by shrek-uberr** [comment]
very very small chance it's related but theres some images on discord running around that windows thinks is a trojan cause it has this at the end of the image data 
![image](https://user-images.githubusercontent.com/82292471/118119470-68e51800-b3bc-11eb-94b0-86b946140f18.png)
kinda funny tho

**Comment by lolPants** [comment]
Closed due to v1.1.20 seemingly not being flagged
