### ISSUE TITLE
Update to support game version 1.16.0

### ISSUE THREAD

**Issue by CTJansson** [Assistant/ModAssistant#348]
Seems developers stealth released 1.16.0 and caused all mods from modassistant to stop working.

![image](https://user-images.githubusercontent.com/8863468/119870514-bff0fe00-bf21-11eb-8ae7-5013e05f9329.png)

**Comment by DeadlyKitten** [comment]
This is intended behavior. If you check https://beatmods.com, you will see that there are currently no mods released for 1.16.0
Once they are, they will show up in Mod Assistant.
