### ISSUE TITLE
How do i install this if my beat saber installation is on my quest?

### ISSUE THREAD

**Issue by Los-3r** [Assistant/ModAssistant#351]
Im trying to gt this so that i am able to install SiraUtil to install Trick Saber, but i cant choose where my beat saber installation is, because it is on my quest (and quest files are inaccessible by file explorer.)

**Comment by lolPants** [comment]
ModAssistant is for PC Modding only. I suggest you visit the `#quest-help` channel on the [BSMG Discord](https://discord.com/invite/beatsabermods) for help modding the quest version of Beat Saber.
