### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by SpoonMcForky** [Assistant/ModAssistant#355]
After months of not playing, I hoped that I could just start up the game and play, boy was I wrong! The first time I launched I got a black screen after the health and safety warning, looked and up, and apparently, I needed to use the beta, but I couldn't use mods so I said screw it and continued to run stable. Every single time I closed the game I would have to validate files to launch the game. Without doing so, the play button would say running for about 100ms before going back to play. I narrowed the mods down to _song core_., how wonderful. Is anyone else having this issue? I'm on the latest mod assistant and I've reinstalled about 5 or 6 times, on every single one of my storage drives

**Comment by lolPants** [comment]
This repo is not the correct place to solicit help with mods. This is purely a bug tracker for ModAssistant itself. Head to `#pc-help` in the [BSMG Discord](https://discord.com/invite/beatsabermods) instead.
