### ISSUE TITLE
Failed to get the game directory due to Steam changing the libraryfolders.vdf format

### ISSUE THREAD

**Issue by WGzeyu** [Assistant/ModAssistant#361]
Recently, many people in the Chinese community reported that modassistant could not find the installation directory, and then I installed BeatSaber on other hard drives for testing and reproduced the situation.
I used to do a similar program to get the game catalog through Steam, and now it also doesn't work. After careful inspection, I found that the format of `libraryfolders.vdf` has changed after the Steam update. After modifying the matching method, it worked.
It's just that I don't know regular expressions, so I'm not particularly sure.
https://github.com/Assistant/ModAssistant/blob/c9ba3d0a133a35d02578376aac050ec66a53778f/ModAssistant/Classes/Utils.cs#L197-L240

**Comment by lolPants** [comment]
I don't appear to have any changes to my `libraryfolders.vdf` file, an example of the new format would be appreciated.

**Comment by WGzeyu** [comment]
[https://wgzeyu.gtxcn.com/img/bs/libraryfolders.vdf](https://wgzeyu.gtxcn.com/img/bs/libraryfolders.vdf)
```
"libraryfolders"
{
	"contentstatsid"		"-8451083859751176344"
	"1"
	{
		"path"		"D:\\SteamtestLibrary"
		"label"		"Yuan4T"
		"mounted"		"1"
		"contentid"		"957069605755048665"
	}
}
```

**Comment by WGzeyu** [comment]
I found that it seems that the `libraryfolders.vdf` will be changed to the new format after re-saving the library folder settings.
The previous format will still be used without changing the settings, so it may be necessary to be compatible with both the old and new formats.

**Comment by lolPants** [comment]
@WGzeyu can you test if [this build](https://github.com/Assistant/ModAssistant/suites/3151846613/artifacts/72467481) works for the new format.

**Comment by WGzeyu** [comment]
> @WGzeyu can you test if [this build](https://github.com/Assistant/ModAssistant/suites/3151846613/artifacts/72467481) works for the new format.

it works
