### ISSUE TITLE
*No mods available for this version of beat saber*

### ISSUE THREAD

**Issue by Majorkrabbe** [Assistant/ModAssistant#367]
Hi.  Got this message fro mod assistant. I did delete the previous, but that did not help. What to do?
The game version is 1.16.3. I can not choose any one newer.

Keep up the great work.

Best regards Kenneth

**Comment by carly-mizzou** [comment]
Same here. Discord channel says it's being archived as Mods on that channel are no longer supported on version 1.16.3
I can choose an older version in the Mod assist, but I assume that won't be applied to the game. Hoping there's....hope? for all my custom songs etc...

**Comment by rhnorskov** [comment]
> Same here. Discord channel says it's being archived as Mods on that channel are no longer supported on version 1.16.3
> I can choose an older version in the Mod assist, but I assume that won't be applied to the game. Hoping there's....hope? for all my custom songs etc...

You can roll back the Beat Saber version to 1.16.2.

Using [DepotDownloader](https://github.com/SteamRE/DepotDownloader), run the following command to download.
```
dotnet DepotDownloader.dll -app 620980 -depot 620981 -manifest 3692829915208062825 -username YOUR_USERNAME -password YOUR_PASSWORD
```
Then copy the files from `depots\620981\7028197` to the Beat Saber folder e.g. `C:\Program Files (x86)\Steam\steamapps\common\Beat Saber`

**Comment by LordNecton** [comment]
Im having the same problem I really hope theres a update coming soon...I dont want to roll back the game as i also play online

**Comment by lolPants** [comment]
This is not an issue with ModAssistant, this is intended behaviour. Be patient and mods for the new version of Beat Saber will be available soon.
