### ISSUE TITLE
Error in About Tab when clicking on "Headpats" or "Hugs"

### ISSUE THREAD

**Issue by XCraftTM** [Assistant/ModAssistant#368]
I just wanted to look around in Mod Assistant and found out that you can click on the two buttons in the about Tab. So i Tried that, but these just spitted out errors and closed the Mod Assistant.
![Screenshot_1](https://user-images.githubusercontent.com/72396660/126635593-08cf9335-881b-4b0d-a07c-d955f338dd6b.png)

I Don't know why that happens but i can't be a normal thing...

**Comment by Melopod** [comment]
See issue #102
