### ISSUE TITLE
beatsaber messed up with new update

### ISSUE THREAD

**Issue by Themonts8007** [Assistant/ModAssistant#369]
my mod assistant is working nor my beatsaber after the new update can some one help me.

**Comment by LordNecton** [comment]
Yours and everybodys is messed up...Have to wait for a update to Mod Assistant

**Comment by Melopod** [comment]
ModAssistant requires no updates.
Mods have simply not been updated for the newest version of the game. Please be patient

**Comment by lolPants** [comment]
Duplicate of #367
