### ISSUE TITLE
One click install issue

### ISSUE THREAD

**Issue by xana43** [Assistant/ModAssistant#37]
When ever I try to do a one click install, from either modelsaber or beatsaver, the mod assistant always pops up a windows 10 notification saying "Unrecognized argument, closing mod manager"

**Comment by Assistant** [comment]
If it says "Mod Manager" and not "Mod Assistant" it sounds like you have Mod Manager registered to use OneClick Installs, in which case you need to unregister it and register Mod Assistant to do it.
