### ISSUE TITLE
Version 1.16.4 - forced updated by steam

### ISSUE THREAD

**Issue by avielc** [Assistant/ModAssistant#371]
Hi guys
First of all thanks for all your hard work and effort to bring this great mod tool to everyone. Thank you!

BeatSaber 1.16.4 on Steam has been released 2 days ago, 
Normally I wouldn't mention it (following the issue before last) 
Unfortunately I can't hit play without updating the game first. 
Any ideas what can be done about it? 
Do everyone have to wait until a patch will be released?
Thanks!

**Comment by Melopod** [comment]
Unfortunately, as your question has nothing to do with Mod Assistant, this isn't the place to ask.
Maybe check some Steam forums instead, they'll be able to help you better.

**Comment by avielc** [comment]
Got it. 
Thanks for commenting!
