### ISSUE TITLE
I cant download songs

### ISSUE THREAD

**Issue by Lionndd** [Assistant/ModAssistant#376]
I FOLLOWED ALL THE STEPS. But in the app when i select the news songs , i cant click in the download botton.
Why?

**Comment by LudoW809** [comment]
This is happening to me even after a fresh install of beatsaber

**Comment by LudoW809** [comment]
Also mod assistant fails on downloading songs at all, I suspect its an issue with where the songs are hosted... 
any info would help greatly

**Comment by LudoW809** [comment]
SOLVED:
beatsaver.com is under maintenance and will be back up later

**Comment by RisinAgainst** [comment]
I too am having issues trying to search for songs, uninstalled all files and folders, deleted left over folders fresh install, when searching for a song nothing loads, but if I goto sort and select something I get those to load but nothing for searching songs

**Comment by Melopod** [comment]
I suggest reading the final comment right above yours.

**Comment by Revadike** [comment]
beatsaver.com is not down for me, and I also can't download songs

**Comment by LudoW809** [comment]
> beatsaver.com is not down for me, and I also can't download songs

Yes, the front end it up, but the back end for actually doubling songs may not,
I tested it just now and can confirm that, You CAN download songs.

Just be mindful that the first comment was 9 hours ago,
Beatsaver.com may still be fixing little things here and there

**Comment by Revadike** [comment]
I still get
![image](https://user-images.githubusercontent.com/4411977/128269729-cf5e52cb-1335-4644-9cc9-3488806c18bd.png)

Fresh install

**Comment by LudoW809** [comment]
> I still get
> ![image](https://user-images.githubusercontent.com/4411977/128269729-cf5e52cb-1335-4644-9cc9-3488806c18bd.png)
> 
> Fresh install

Please read the above comments before postin,

Beatsaver Is Under Maintenance for a unknown amount of time!
And thus, you will not be able to download songs until its back up.

**Comment by Revadike** [comment]
My apologies, I did read the above comments, but I thought they said maintenance is over now.

**Comment by LudoW809** [comment]
> My apologies, I did read the above comments, but I thought they said maintenance is over now.

The frontend website is up, but the backend api for downloading maps, is most likely still under maintenance

**Comment by Assistant** [comment]
That screenshot isn't even Mod Assistant. 
The OneClick Installer feature of Mod Assistant to download songs is fixed and an update will be released shortly which should automatically take place when you restart Mod Assistant, however that will not fix the issues unrelated to Mod Assistant that are erroneously being reported here.

**Comment by SlayerZiron** [comment]
I am seeing the same thing in Beat Saber, even though I have songs downloaded I have no clue how to reach them and can only find a library of unloadable songs under the 'More Songs' tab.

**Comment by LudoW809** [comment]
> I am seeing the same thing in Beat Saber, even though I have songs downloaded I have no clue how to reach them and can only find a library of unloadable songs under the 'More Songs' tab.

Read the comment, riiiiight above your one.

**Comment by SlayerZiron** [comment]
Ye I read it just I am a first time user and am not sure what that means for me or what I should be doing to fix the issue.
"however that will not fix the issues unrelated to Mod Assistant that are erroneously being reported here." does this mean that my issue will be fixed in the update that is coming soon or that I am doing something wrong?

**Comment by LudoW809** [comment]
> Ye I read it just I am a first time user and am not sure what that means for me or what I should be doing to fix the issue.
> "however that will not fix the issues unrelated to Mod Assistant that are erroneously being reported here." does this mean that my issue will be fixed in the update that is coming soon or that I am doing something wrong?

"however(the update) will not fix the issues unrelated to Mod Assistant"

The website Beatsaver is currently Under Maintenance, and you will not be able to downlod songs until it is back up.

This is not an issue with Mod Assistant, but rather beatsaver.

While the website may appear to be online from the front,
The backend is most likely still undergoing fixes!

**Comment by SlayerZiron** [comment]
I didn't download songs through Beatsaver I was using BeastSaber

**Comment by DeadlyKitten** [comment]
BeastSaber hosts not songs of its own, rather it uses BeatSaver behind the scenes.

**Comment by SlayerZiron** [comment]
Ohh okay ty

**Comment by LudoW809** [comment]
Assistant

Please close the thread

**Comment by Assistant** [comment]
Issues **inside** of the game aren't issue with Mod Assistant, as Mod Assistant doesn't modify any ingame behavior, it simply serves as an installer for other programs and assets that do. Therefore if you're trying to download songs ingame, you're not using Mod Assistant to do so, but another program that Mod Assistant installed. Those issues will be fixed once that other program is updated, and its new version installed through Mod Assistant.

The Mod Assistant update that allows you to download songs through the OneClick Installer **outside** of the game is now fixed and released, restarting Mod Assistant, and possibly needing to unchecking and rechecking the option, will work.

**Comment by Revadike** [comment]
https://github.com/Kylemc1413/SongCore/issues/60

**Comment by LudoW809** [comment]
> [Kylemc1413/SongCore#60](https://github.com/Kylemc1413/SongCore/issues/60)

the correct GitHub would be the one for the "More songs" mod, not song core
