### ISSUE TITLE
Download custom songs button is greyed out

### ISSUE THREAD

**Issue by wenishacker** [Assistant/ModAssistant#378]
I followed the usage settings and everything and just reinstalled Mod Assistant to 1.1.23 and the download button in-game for custom songs is still greyed out, PLEASE HELP!

**Comment by Assistant** [comment]
Issues **inside** of the game aren't issue with Mod Assistant, as Mod Assistant doesn't modify any **ingame** behavior, it simply serves as an installer for other programs and assets that do. Therefore if you're trying to download songs **ingame**, you're not using Mod Assistant to do so, but another program that Mod Assistant installed. Those issues will be fixed once that other program is updated, and its new version installed through Mod Assistant.

**Comment by wenishacker** [comment]
Thank you! :)
