### ISSUE TITLE
One click install no longer working

### ISSUE THREAD

**Issue by Gullidion** [Assistant/ModAssistant#379]
One click install has worked fine up to this point, even on this current version. Today however downlaoding songs off of Beastsaber and Beatsaver has resulted in the modassistant window saying 
"Done'd
Download failed: https://api.beatsaver.com/maps/id/1ac68
Installing: 1ac68"

**Comment by LudoW809** [comment]
> One click install has worked fine up to this point, even on this current version. Today however downlaoding songs off of Beastsaber and Beatsaver has resulted in the modassistant window saying
> "Done'd
> Download failed: https://api.beatsaver.com/maps/id/1ac68
> Installing: 1ac68"

This isn't a problem with mod assistant, I would be contacting the makers of beatsaver as its a problem with their servers which host the maps

**Comment by lolPants** [comment]
Not an issue with ModAssistant
