### ISSUE TITLE
Small lag spike whenever checking mods

### ISSUE THREAD

**Issue by Parapass** [Assistant/ModAssistant#380]
Whenever I go to click on the checkbox for the mod I want to install, ModAssistant pauses for about a second and then checks the checkbox.

Here is a video showcasing the bug.

https://streamable.com/8ybws8

**Comment by sourcelocation** [comment]
has this been fixed? The lag spike on linux using wine is significantly worse - 45 seconds

**Comment by Parapass** [comment]
Wasn't fixed because of a visual bug where dependencies (like SiraUtil or CatCore) for mods weren't selected. A PR was made to fix both of the issues but was never merged. I would also recommend using BeatSaberModManager instead of ModAssistant because it's a native Linux appimage.
