### ISSUE TITLE
What happened to Beat Together?

### ISSUE THREAD

**Issue by XPoplyX** [Assistant/ModAssistant#384]
Me and my friend are trying to connect to each other's games and nothings working. We both have the exact same mods installed. But they cant play together, cant even get into each other's server. (CRF - 5)

Wasn't there a mod called Beat Together in Mod Assistant?? What happened?

**Comment by Melopod** [comment]
Mod Assistant only provides the ability to download and install mods. It does not maintain any of the mods provided. The information you're looking for would more likely be on the BeatTogether GitHub, not on this one.

**Comment by lolPants** [comment]
https://github.com/pythonology/BeatTogether
