### ISSUE TITLE
ModAssistant is downloading new versions forever

### ISSUE THREAD

**Issue by Renaud11232** [Assistant/ModAssistant#390]
Hello,

I tried to start ModAssistant just now.
Ususally when there's a new version, it's downloaded then the new version starts. But today, It looped trying to download new versions endlessly.
After a few minutes of downloading new versions, it finaly starts with a message saying it couldn't check for newer versions. Maybe it's some GitHub rate limiting ?
I see the new version is `1.1.24` but the file [AssemblyInfo.cs](https://github.com/Assistant/ModAssistant/blob/master/ModAssistant/Properties/AssemblyInfo.cs) still reports `1.1.23`. maybe it is linked ?

Thanks

**Comment by YorVeX** [comment]
I was just about to report that the version in the bottom left still says v1.1.23 although I am running v1.1.24. I am quite sure that is what leads to the download loop.

**Comment by Assistant** [comment]
Should be fixed in 1.1.25
