### ISSUE TITLE
Mod Assistant not working

### ISSUE THREAD

**Issue by draconinjari** [Assistant/ModAssistant#393]
Over the past couple of days and versions, Mod Assistant refuses to open. The longest it was open was when it was stuck in the boot loop of 1.1.24. The program successfully updated to 1.1.25 but I am still having the same issue that when I attempt to open the program nothing happens except the little blue loading circle next to my cursor.  I have turned off defender, ran the program in administrator and even did the good ol' reboot to no avail.

**Comment by lolPants** [comment]
If this is still happening I'm going to need more detail. Some reproduction steps would be amazing but by the sounds of it you're having a weird one-off issue.

**Comment by draconinjari** [comment]
It is no longer happening. Went on the discord and was advised to move the .exe to anywhere but my downloads folder. For whatever reason, Mod Assistant will not run out of the downloads folder. It now resides on my desktop and I haven't had any issues since.
