### ISSUE TITLE
Detection as trojan in VirusTotal

### ISSUE THREAD

**Issue by JWTSN** [Assistant/ModAssistant#394]
After downloading from the releases tab, I ran it through VirusTotal and it came up as "Trojan.Malware.300983.susgen" in MaxSecure and "Malicious" in SecureAge APEX but no other vendors. I believe this is a false positive but a may be wrong becasue I'm not an expert in this.

VT detection: https://www.virustotal.com/gui/file/78c045295ee35b9152e173ae81ef7ab4cabd62bb91b7ccba627a60779d51e72c/detection

**Comment by Assistant** [comment]
They are false positives, probably a combination of not being signed (certificates cost money) and downloading things from the internet that made it sketchy enough to call it malware in the eyes of those AVs. You can audit the source code to see that nothing malicious is going on and even compile it yourself to be sure that the binary is exactly what the source says it is, but the compilation is taken care of by Github Actions, so afaik that's transparent enough to be sure that it is without having to compile it yourself.
