### ISSUE TITLE
I have both Steam and Oculus versions, only works for Steam Version

### ISSUE THREAD

**Issue by viscoci** [Assistant/ModAssistant#4]
Attempting to change the folder path to my Oculus installation path did not work either.

**Comment by Assistant** [comment]
Can you elaborate what you mean with it doesn't work?

**Comment by viscoci** [comment]
Apologies, in a rush today and I now feel foolish.
When I first ran the application it automatically chose my Steam installation. When I attempted to switch the install folder path to my Oculus installation path, it did not change anything.

However, after restarting ModAssistant.exe it appears to have resolved itself.

**Comment by yoeyyutch** [comment]
Cool. Thanks for the update. Here goes nuthin.....
