### ISSUE TITLE
Error on program startup

### ISSUE THREAD

**Issue by Jakester5112** [Assistant/ModAssistant#41]
https://imgur.com/FZUjIMo

Every time I start the program up this error pops up. It started today (worked fine yesterday). Reinstalling didn't help. Closing the error box crashes the program.

**Comment by Jakester5112** [comment]
It was installed in the Beat Saber directory before. I moved it to downloads and it opens now. However, I try to install a new mod and get this error. https://imgur.com/tX7NAKM

**Comment by Aydekins** [comment]
Can you please provide some reproduction steps? What mod were you trying to install?

**Comment by JamesKaret** [comment]
same happens to me after update to 1.4.0
but before that, it shows that it couldn't load game version with other popup.
(Reinstall didn't help. game and mod)

Could not load game versions, Mods tab will be unabailable.
System.Net.WebException: The remote server returned an origin SSL certificate error (526)
location: System.Net.HttpWebRequest.GetResponse()
location: ModAssisstant.MainWindow.ctor()

**Comment by blackoutfpv** [comment]
> same happens to me after update to 1.4.0
> but before that, it shows that it couldn't load game version with other popup.
> (Reinstall didn't help. game and mod)
> 
> Could not load game versions, Mods tab will be unabailable.
> System.Net.WebException: The remote server returned an origin SSL certificate error (526)
> location: System.Net.HttpWebRequest.GetResponse()
> location: ModAssisstant.MainWindow.ctor()

Same here, just bought an original copy of beat saber, installed it through steam on a different hard drive and deleted the old pirated folder, game version button is grayed out.

**Comment by Kidsnd274** [comment]
Just found out https://beatmods.com/ is down atm. That's probably why.
