### ISSUE TITLE
BeatSaber 1.19.0 released and ModAssistant not working anymore.

### ISSUE THREAD

**Issue by delaware1999** [Assistant/ModAssistant#425]
On 09.12.2021 the Beat Saber Version 1.19.0 was released..
Is there any release date for new Modassistand Version that will work again ??

**Comment by Assistant** [comment]
Mod Assistant is version agnostic, it does not need updates when the game updates. 
Mods themselves will be available once they're updated and pass QA.

**Comment by delaware1999** [comment]
ah oh did not know that and this massage and info did not show up in ModAssistant.. How should I know that ?

**Comment by C4Wiz** [comment]
Beat saber modding group on discord, modding-announcements is the channel,

it lists releases and when it’s safe to upgrade to keep your mods

![11EF5C7F-E95F-45D5-849F-BE4CD026EA3B](https://user-images.githubusercontent.com/3883521/146391603-c791abff-330f-4745-be0b-f8cacf62bf80.png)

**Comment by C4Wiz** [comment]
Update:

![40A00E7E-4F88-4D93-8BA3-144A94D4798B](https://user-images.githubusercontent.com/3883521/147093725-27efa3a7-8c45-4cf2-8e5f-2667a6e3c191.jpeg)
