### ISSUE TITLE
"No mods available for this version of Beat Saber" for game version 1.19

### ISSUE THREAD

**Issue by Fan-Mi** [Assistant/ModAssistant#428]
Hi,

I got this message after the Lady Gaga update. I saw there is a pinned discussion in August relating to this. But I'm still confused and would like to know is it a designed feature (rather than my own mistake installing it)?

Thanks!

**Comment by Assistant** [comment]
Yes, that message shows up when there aren't any mods available for the detected version of Beat Saber.

**Comment by TomPatelGaming** [comment]
This happened just now with the 1.20 update

**Comment by DeadlyKitten** [comment]
This will happen with every update that brings breaking changes (like 1.20) because there are no mods for the new version yet.
