### ISSUE TITLE
Suggestion: Add a link to this GitHub on the About page

### ISSUE THREAD

**Issue by Garywoo** [Assistant/ModAssistant#43]
So I can come check on updates and issues without having to google for it 😘

**Comment by TheLawsOfChaos** [comment]
lol +1, when BeatSaber gets updated, I manually come here to look (though I just go to github and looked at my star'ed repos.

**Comment by DeadlyKitten** [comment]
Mod Assistant is not dependent on game version, and as such doesn't need to be updated when the game does. If there ever is an update, Mod Assistant will notify you on launch and then update itself.
