### ISSUE TITLE
There is no custom sabers on mod assistant

### ISSUE THREAD

**Issue by Lion123-I** [Assistant/ModAssistant#441]
I have noticed that for a while there hasn't been the "custom saber" mod on mod assistant since I think the last update. I would just like to know what could be the possibility.

**Comment by Melopod** [comment]
Mod Assistant doesn't provide mods on its own, all it does is pull mods for a specific version from a site/repository called BeatMods. If it's not available on Mod Assistant, it's not an MA problem, it's that the mod has not been uploaded/approved by the mod's maintainer, of which there are countless reasons for not having been done.
Hope this answers your question.
