### ISSUE TITLE
Not Uploading Scores

### ISSUE THREAD

**Issue by TheCDog06** [Assistant/ModAssistant#447]
I updated Beat Saber and now my scores don't upload, but all the other mods still work. I uninstalled and reinstalled all mods but it still won't upload any new plays.

**Comment by Autobot9000** [comment]
Hi, I am having the same issue, is there a fix?

**Comment by Melopod** [comment]
Mod Assistant doesn't handle this. It's not a mod, all it does is install mods for you. It doesn't handle anything related to in game
