### ISSUE TITLE
v1.20.0

### ISSUE THREAD

**Issue by fa0311** [Assistant/ModAssistant#449]
ModAssistant doesn't work on v1.20.0

**Comment by maxwell-01** [comment]
Confirmed, just a message that says "No mods available for this version of Beat Saber"

**Comment by Melopod** [comment]
It means exactly what it says. There are no mods currently available or updated for this version of Beat Saber.

**Comment by maxwell-01** [comment]
Ahh. Very good point sir, sorry for the bother.
