### ISSUE TITLE
v1.21.0

### ISSUE THREAD

**Issue by wind111-lang** [Assistant/ModAssistant#452]
ModAssistant said "No mods available for this version of Beat Saber"

**Comment by Assistant** [comment]
As the message says, that means there are no mods available for that version of Beat Saber.

**Comment by ZaberModder** [comment]
Hello,

I do have a few questions, hopefully one our modding gurus can explain.

I had been using Mod assistant up until beat saber 1.19.0, and it was fabulous, amazing, everything I want it to be.

So, 1.20 came out, and you said no mods available, so everything back to stock form.

however, about a week ago, mods started showing up, nevertheless, even though I install them, none of them show up in beat saber.

Is this a bug?

I'm looking at my beat saber on my pc right now, I updated my beat saber to 1.21.0, I uninstalled all mods, then all the mods continue to appear in the MODS page for version 1.21.0, I just installed all the available mods in the MODS page, but what if once I fire up beat saber, I still see no Mods take effect? just as it was the case in version 1.20.0 of beat saber. 

Even though there are mods, they just don't show up on beat saber.

Isn't it supposed to be a new version of Mod Assistant as well? shouldn't we be on 1.1.27 be now? I have seen all the updates in the past year, and almost every time there is a beat saber update, a new Mod Assistant updated version comes out within a week. However, this time around, the current version 1.1.26 was launched in August 2021, shouldn't we have a new version by now? 

Gut feeling is telling me the ModAssistant version 1.1.26 isn't working for any beat saber after 1.19.0, so what is the point of the program showing the available mods?

Thank you for your time and help, I mean no disrespect, I simply truly enjoy playing with the amazing mods that the entire community has so masterfully developed. 

Am I doing something wrong?

**Comment by ZaberModder** [comment]
here is a screen shot
![image](https://user-images.githubusercontent.com/102780658/161193361-04bea180-c86b-4f30-add9-027bf66f642b.png)

**Comment by Assistant** [comment]
> Isn't it supposed to be a new version of Mod Assistant as well? shouldn't we be on 1.1.27 be now? I have seen all the updates in the past year, and almost every time there is a beat saber update, a new Mod Assistant updated version comes out within a week. However, this time around, the current version 1.1.26 was launched in August 2021, shouldn't we have a new version by now?

Mod Assistant has **never** been updated to support new versions of the game, if there has been updates following a game update that is purely coincidental. Mod Assistant is completely version agnostic, it does not interface in any way with the game.

I recommend visiting the #pc-help channel in the [BSMG Discord server](https://discord.gg/beatsabermods), where you can get help troubleshooting your install.

**Comment by ZaberModder** [comment]
Oh, that is interesting to know. 

Then if it doesn't interface with the game in any way, why do the mods become unavailable when a new Beat Saver version is released?

It surely seems like there must be some type of interaction between mod assistant and beat saber, otherwise the mods would work always regardless of what version of beat saber is released no?

**Comment by wind111-lang** [comment]
I checked Mod list appear. sorry for the inconvenience...

**Comment by Assistant** [comment]
> Then if it doesn't interface with the game in any way, why do the mods become unavailable when a new Beat Saver version is released?
> 
> It surely seems like there must be some type of interaction between mod assistant and beat saber, otherwise the mods would work always regardless of what version of beat saber is released no?

When a new version of Beat Saber is released, modders check to see if the old mods are working, if they do not work they create a new version on BeatMods, since that version contains no mods Mod Assistant will display the message saying no mods are available, until the mods are updated to work with the new version of Beat Saber, uploaded to BeatMods, and approved. Mod Assistant doesn't contain any mods, it's simply a tool to download and install mods from BeatMods.
