### ISSUE TITLE
Issue with UITweaks Mod

### ISSUE THREAD

**Issue by ZaberModder** [Assistant/ModAssistant#454]
Hello,

I wanted to report an issue with the UITweaks mode. I finally pinpointed to this specific mod, regarding to the issue I was having.

I love this mod, and it is unfortunate that it is having this issue, as it is very annoying.

After playing and completing a song, when you try to play a second song, the app will crash, you have to force close beat saber, and go back to the virtual home desktop, then you have to restart beat saber, and then you can play another song. But this happens every time after playing 1 song during that session. 

Hope this helps and that the bug can be resolved, as the color mod on the x meter is really great to keep track of it without looking at it directly. 

Thank you!

**Comment by DeadlyKitten** [comment]
Hello,

This repository is only for ModAssistant itself, not the mods. You should file an issue on the [UITweaks GitHub page](https://github.com/Exomanz/UITweaks).
