### ISSUE TITLE
Version 1.1.26 not present on GitHub?

### ISSUE THREAD

**Issue by osiris-plus** [Assistant/ModAssistant#458]
I don't remember if I got this from GitHub, strangely now there's only version 1.1.25 available, is it supposed to be like this?

SHA1 I have: 8D875587D41475FE58674041847E2F759BCEF031

**Comment by Assistant** [comment]
Thanks for the report. I have no idea why the 1.1.26 release wasn't showing up, but I've fixed the issue.
