### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Auroya** [Assistant/ModAssistant#46]
BeatSaber recently had an update, and since then, I have not been able to use the mod assistant in the game. I am not extremely tech savvy, so I don't know where to start with a fix. What I can add is that the Oculus works fine, other games work fine, and Beat Saber works fine if I disable all the mods in the mod assistant. I then don't have any of the previously downloaded songs, high scores, or any of the mods.

**Comment by Assistant** [comment]
This program isn't dependent on Beat Saber in any way, and doesn't require updating when Beat Saber updates.
[https://bsmg.wiki/support](https://bsmg.wiki/support)
