### ISSUE TITLE
Beatsaber locks up after pressing start on any song just with mods

### ISSUE THREAD

**Issue by FilipLac** [Assistant/ModAssistant#466]
Hi,
since updating to newest version of beatsaber I am unable to play any song with mods installed.
When I completely uninstalled beatsaber and did clean install it worked as expected. But after using modAssistant app to install desired mod, pressing play just fades whole game to black and locks it up in this state.
Any idea on how can I fix this issue and make it function normal again, or is it known issue?

Steps to reproduce:
Install Beatsaber (open and close it when clean installed)
Download and open ModAssistant
Install desired mods (like mapping extension, cam mod, noodle extension and few more)
Start game and play whichever song you like (build in once will have this issue too not just custom songs).
After hitting play menu just fades to black but nothing else happens.

Expected is that song should start playing after fading to black.

**Comment by Melopod** [comment]
This is a modding issue, not a Mod Assistant issue. MA only serves to install mods, it doesn't affect the game otherwise.
Please refer to the troubleshooting part of the wiki at bsmg.wiki or the support channels in the BSMG discord server at discord.gg/beatsabermods

**Comment by FilipLac** [comment]
Well, after looking on this issue I found out that for some reason mod assistant kept SaberFactory in new plugins folder but it wasn't compatible with this new version.
That's why I would lock up (errors in console showed missing methods and shaders).
Removing all plugins and reinstalling mods for new version fixed this issue (but SaberFactory is still unavailable).
