### ISSUE TITLE
BeatSaber 1.25 can't press play with mod installed

### ISSUE THREAD

**Issue by therhemis** [Assistant/ModAssistant#476]
With the update of BeatSaber to 1.25, I can't press play on any song (custom or official) with any mods installed.

**Comment by mryabets** [comment]
Just FYI: you can still play by creating a private multiplayer server.

**Comment by rgcv** [comment]
I found that a couple of mods such as Chroma and NoodleExtensions still aren't up to date and won't work with 1.25.0 at time of writing.  What I suggest is you uninstall everything, BSIPA included, and install everything again.  If you're still running into the same issue, try removing the folders manually from the BeatSaber install folder (plugin-related things only, not data! keep that if you want custom songs, notes, avatars, etc.).  Then try cleanly reinstalling.  That did the trick for me.

**Comment by d-uzlov** [comment]
I remember having this issue when I had ScoreSaber installed. Apparently it disables the Play button until the connection with scoresaber servers is established.
If the servers are unavailable for any reason, the button will remain disabled forever.
I haven't tried installing scoresaber ever again, so I don't know if this is still an issue.

**Comment by RoboPenguin7** [comment]
> 

Thankyou, firewall was blocking scoresaber, so that's what caused the issue.

**Comment by xXPerditorXx** [comment]
For me, it is "heck" which is blocking me from pressing play. The problem is, that it is the main lib if Chroma and NoodleExtension which is needed to play many songs.
