### ISSUE TITLE
Need Solution for Quest Users

### ISSUE THREAD

**Issue by automan25** [Assistant/ModAssistant#48]
This program seems to require the install folder for BeatSaber on your PC. Quest users have no such folder, but would still like to make custom songs and side-load them to the Quest. Perhaps there's a way to trick ModAssistant into thinking it has found the BeatSaber install folder? I tried this, but ModAssistant insists it hasn't found the BeatSaber install folder. Are there dependencies from the PC version of BeatSaber that ModAssistant requires in order to function?

**Comment by daniel11420** [comment]
ModAssistant is designed for the PC Version of Beat Saber -- if you'd like to install mods on Oculus Quest, you could follow [this guide](https://bsaber.com/beaton/) to install songs/mods.
