### ISSUE TITLE
BeatSaber v1.28.0 has been released

### ISSUE THREAD

**Issue by daniloff200** [Assistant/ModAssistant#496]
Perhaps, I shouldn't create this issue, but, just in case, and to track all stuff, related to v 1.28.0
So, today it was released, and our favorite tool for this game now doesn't working

I'm a new guy to the community, and today, after few months of using this app I can't imagine how to play BeatSaber without it.
No mods,  some of the custom songs are broken, leaderboards too :( 

Waiting for a fast release of ModAssistant! Thank you for your work!

**Comment by ikenami** [comment]
Had the same issue with the recent update.
This thread fixed it for me: https://steamcommunity.com/sharedfiles/filedetails/?id=2835143135

**Comment by Melopod** [comment]
This assumes that the mods for the previous version still work for the current version. Please don't make this assumption, and rather keep an eye on the #modding-announcements channel in the BSMG Discords server instead. Whether or not mods are compatible for the current version of the game is posted with every update

**Comment by JanieUwU** [comment]
> Had the same issue with the recent update. This thread fixed it for me: https://steamcommunity.com/sharedfiles/filedetails/?id=2835143135

I did what it said but Mod Assistant still says there are no mods for that version of the game :<

**Comment by Trackhe** [comment]
What is the normal update intervall of the mods? I ask because of the 1.29,
