### ISSUE TITLE
Could not load game version error

### ISSUE THREAD

**Issue by AndryGabry01** [Assistant/ModAssistant#50]
When i open mod assistant, it tell me this error: 
![download](https://user-images.githubusercontent.com/25670766/66578758-f37bea80-eb7b-11e9-8472-edd090f64b3b.png)

what can I do?

**Comment by CupricReki** [comment]
Beatmods is currently running an invalid SSL cert. The problem is on their end. You'll see the same error (526) when you browse to their webpage.

**Comment by AndryGabry01** [comment]
Do you know if the site has communicated anything, perhaps through some social media?

**Comment by CupricReki** [comment]
It's back now.
