### ISSUE TITLE
BeatSaber 1.29.4 support

### ISSUE THREAD

**Issue by Youw** [Assistant/ModAssistant#503]
A new version of BeatSaber has been released.

Any work being done to get suppor for it?

Any help needed?

**Comment by SpartanA60** [comment]
Hello there, yes i need help.
i want to download some mod with de mod assistant but it tell me that there is not mod fount with these version.
is it normal ?
( sorry for my bad english lol )

**Comment by Melopod** [comment]
This recent version update includes a new Unity version update that requires a lot of work for mods to be maintained. If you would like to use the previous version's mods, you can downgrade temporarily to the previous version of the game via the beta channels on Steam or Quest, or more permanently with downgrading tools.

That being said, here's a couple points about how it all works:

- Mod Assistant is only a tool that provides easy installation of mods, compiled on BeatMods. MA itself has nothing to do with which mods are available or not, it just lists them when approved. It does not require any updates when the game does.

- Mods not being available when a game update releases is normal! While some mods may work with new versions as the code they're based on doesn't change, most of the time mods rely on code that changes, and therefore need to be updated themselves. Please be patient as modders are volunteering their time to maintain these mods, and it may take some time for things to be updated again.

Hope that clears things up! If you need any more help, please join the Beat Saber Modding Group at discord.gg/beatsabermods

**Comment by Youw** [comment]
Cristal clear, thanks.
@Melopod while all you've described becomes almost obvious after you've explained it, unfortunately a _quick_ googling doesn't give that impression.

Do you have contacts with the maintainer(s) of this repo? Maybe add a Wiki/F.A.Q page and paste your message there?
To avoid tickets like this from other users in the future.
