### ISSUE TITLE
No mods available for this version of Beat Saber

### ISSUE THREAD

**Issue by G4419** [Assistant/ModAssistant#504]
Game Version1.29.4 
ModAssitant Version1.1.32

**Comment by Latukk** [comment]
the same problem

**Comment by G4419** [comment]
Thanks. It really helps.

**Comment by didorins** [comment]
> 

I am not your guy, but for me when I select Properties > Betas > Legacy 1.29.1... It changes the Beat Saber "Play" button to Upgrading, so it takes sometime to downgrade. Eventually it will complete. Get in touch with Steam support if you can't downgrade the application using this method.

**Comment by wolfey2900** [comment]
> You can still play with mod if you want until they upgrade to the latest game version by choosing the pre unity upgrade build in the beta tab of the game properties after the update the game should roll back to the 1.29.1
> 
> ![Screenshot 2023-05-15 141630](https://user-images.githubusercontent.com/131216341/238346478-2ffc3cc7-73f2-4f04-bf5d-d2aa761b447b.png)

doing this just crashes beatsaber for me, no mods work

**Comment by Averanthia** [comment]
> > You can still play with mod if you want until they upgrade to the latest game version by choosing the pre unity upgrade build in the beta tab of the game properties after the update the game should roll back to the 1.29.1
> > ![Screenshot 2023-05-15 141630](https://user-images.githubusercontent.com/131216341/238346478-2ffc3cc7-73f2-4f04-bf5d-d2aa761b447b.png)
> 
> doing this just crashes beatsaber for me, no mods work

Hello, sorry for the late answer !

Did you make sure in ModAssitant that the game version was in 1.29.1 when installing the mod or updating them ?
If nothing work i suggest you to try again but with a clean install, don't forgot to remove left over files when uninstalling the game.

Hope it will fix the problem !

**Comment by golddragon007** [comment]
To downgrade to the previous version you can follow this guide: https://www.thewindowsclub.com/how-to-downgrade-steam-games-to-previous-versions
and use the "Revert to previous version of game using Steam Console" instructions, opt-out from beta beforehand.
This worked for me, I have mods, but I'm unsure if I can play online, as I never do it.
