### ISSUE TITLE
ModAssistant is not FIPS compatible.

### ISSUE THREAD

**Issue by jacklollz2** [Assistant/ModAssistant#53]
![image](https://user-images.githubusercontent.com/25973951/68066073-aae1c800-fd08-11e9-8004-1804a912e65f.png)

**Comment by Assistant** [comment]
It doesn't aim to be.

**Comment by jacklollz2** [comment]
That's incredible my guy. You can easily make it FIPS compatible by not using MD5, an ancient hashing algorithm. It's become a basic standard to not use MD5.

**Comment by Assistant** [comment]
If you figure out a way to see if a file is exactly the same as another given only a file and an MD5 hash string, I'm all ears.

**Comment by jacklollz2** [comment]
MD5 is known to have collisions in the past, it's occurred many times. Web servers don't use it specifically for that reason. SHA1 additionally is much easier to implement because MD5 requires consistency checks between a table.
There's an extremely basic Google search I've done so you can understand collisions: https://superuser.com/questions/718220/any-examples-of-duplicate-md5-hashes
There's many other examples, but this one is nice and simple.

**Comment by Assistant** [comment]
Please elaborate, I'm uncertain on how to compare an MD5 hash string with a SHA1 hash string to see if they correspond to the same file.

**Comment by jacklollz2** [comment]
I'm not sure what you're asking. Like I said in my original post, MD5 is unsupported, and you should upgrade the algorithm to at minimum SHA1 to make this program FIPS compliant.

**Comment by Assistant** [comment]
I'm asking how can I use SHA1 to see if a file is exactly the same as another when given an MD5 hash string.

**Comment by jacklollz2** [comment]
The mod website does not use SHA1/256? If not, we both should contact the website host to upgrade the functionality. An example would be the Skyrim mod manager, it used to use MD5 but was updated about a year or so ago. It should be relatively easy to make the Beat Saber mod website updated, since there's such a small amount of mods.

**Comment by Assistant** [comment]
I'm the host of BeatMods, but not the developer, and no one wants to touch that codebase. There's a group a developers working on creating a new one from scratch, but until then I don't see the point when MD5 works fine in this situation. 

MD5 is not as secure as the other hashing algorithms you mentioned, but in this use case it doesn't matter. If you think you can produce an MD5 collision on any of the files currently approved on BeatMods, I challenge you to try.

**Comment by jacklollz2** [comment]
If someone is creating a new one from scratch, then great, I'll wait for proper SHA256 support then. Hopefully that can come soon.

**Comment by qe201020335** [comment]
@jacklollz2 MD5 here is used to check whether the `steam_api64.dll` has been modified, in other to check game piracy.
I think what they mean is they only know the md5s of the real `steam_api64.dll` so they have to use md5
