### ISSUE TITLE
Feature Request: Dark Theme

### ISSUE THREAD

**Issue by bbb651** [Assistant/ModAssistant#54]
Seems like a pretty simple feature to implement that would improve user experience, just a simple dark theme that can be toggled from the settings that would be enabled by default (or using the OS theme).

Sorry that I made an issue instead of a pull request, I don't have experience in C#, it seems like it's a matter of changing the background property of UI components.

**Comment by gabfv** [comment]
I would like this as well.

**Comment by Parapass** [comment]
You can change it by going into Visual Studio and changing the UI components on MainWindow.xaml to be dark, but if you want to add a button to toggle dark mode on options, then you need C#.

**Comment by megalon** [comment]
Themes were added in `Mod Assistant v1.1.0`
See `Settings` -> `Application Theme`
