### ISSUE TITLE
Can't download versions list.

### ISSUE THREAD

**Issue by pokerobplays** [Assistant/ModAssistant#56]
I'm on version 1.6 on beat saber and 1.0.25 on mod assistant. Whenever I click "I Agree" on the intro it says,"Could not download versions list. Mods tab disabled. Please restart to try again." I've tried uninstalling and reinstalling, closing and opening it again but I can't get it to work.

**Comment by Assistant** [comment]
This is not an issue with Mod Assistant. Check to see if your connection to [BeatMods](https://beatmods.com) works.
