### ISSUE TITLE
New Game Version Detected!

### ISSUE THREAD

**Issue by acoop133** [Assistant/ModAssistant#57]
I have the latest Game version

![image](https://user-images.githubusercontent.com/19627023/70857273-224b6f80-1ee3-11ea-8b24-24879ab4898f.png)

**Comment by Assistant** [comment]
I don't understand why this is an issue.

**Comment by acoop133** [comment]
Because when i press OK, it closes the client.

**Comment by acoop133** [comment]
however issue no longer persists after restart it seems...
