### ISSUE TITLE
Possible bug in GetOculusDir() ?

### ISSUE THREAD

**Issue by lansalot** [Assistant/ModAssistant#6]
It's getting late... but
`return SetDir(Path.Combine(OculusInstall + @"Software\hyperbolic-magnetism-beat-saber"), "Oculus");`
should be
`return SetDir(Path.Combine(OculusInstall, @"Software\hyperbolic-magnetism-beat-saber"), "Oculus");`

shouldn't it?

**Comment by Assistant** [comment]
You're right, just fixed it.

**Comment by lansalot** [comment]
Thanks

Was trying to debug why it was returning D:\\OculusSoftware instead of D:\\Oculus\\Software - but man, I'm damned if I can work out where the app is deriving the initial value. I've breakpoints on all the functions that look for it, that set the properties, everything - and somehow, it just seems to be in there already.

I need to spend some time to work out how this XAML/WPF stuff works!

(Great work, by the way!)
