### ISSUE TITLE
Mods don't seem to be added

### ISSUE THREAD

**Issue by Emblin13** [Assistant/ModAssistant#60]
I am using Mod Assistant v1.0.27 on Beat Saber v1.6.0. My game version is set to v1.6.0 in the mod assistant.

After downloading the assistant, selecting the mods I want, and clicking "install or update", I play Beat Saber but none of the mods appear to be added. For example, the custom song finder is not in the game. Other mods such as "NoFailCheck" and "Level Pack Panel Mover" do not appear to be in the game either.

Mod Assistant log: https://p.teknik.io/3jCq1
Beat Saber log: https://paste.gg/p/anonymous/fd5afce835034190baba09c7466289f9

**Comment by NiklasAngare** [comment]
I have the same issue and the same versions. I had mods working fine on previous versions of Beat Saber.

Mod Assistant log: https://p.teknik.io/TrWwP

**Comment by samfun123** [comment]
I had the same issue, these instructions from the Discord helped:
```
1. Update BSIPA using Mod Assistant 
2. Run IPA.exe from the Beat Saber folder
3. Start the game
4. Close the game
5. Install mods using Mod Assistant
6. Start the game
```

**Comment by Emblin13** [comment]
> 
> 
> I had the same issue, these instructions from the Discord helped:
> 
> ```
> 1. Update BSIPA using Mod Assistant 
> 2. Run IPA.exe from the Beat Saber folder
> 3. Start the game
> 4. Close the game
> 5. Install mods using Mod Assistant
> 6. Start the game
> ```

That fix worked like a charm. Thanks!

**Comment by NiklasAngare** [comment]
> I had the same issue, these instructions from the Discord helped:
> 
> ```
> 1. Update BSIPA using Mod Assistant 
> 2. Run IPA.exe from the Beat Saber folder
> 3. Start the game
> 4. Close the game
> 5. Install mods using Mod Assistant
> 6. Start the game
> ```

It worked for me too. In step 2, IPA displayed something about restoring old versions and something about Assembly-CSharp.dll. The file `Beat Saber_Data\Managed\Assembly-CSharp.dll` was missing before but was present after step 2.

**Comment by Blenderpics** [comment]
> I had the same issue, these instructions from the Discord helped:
> 
> ```
> 1. Update BSIPA using Mod Assistant 
> 2. Run IPA.exe from the Beat Saber folder
> 3. Start the game
> 4. Close the game
> 5. Install mods using Mod Assistant
> 6. Start the game
> ```

That only partly worked for me. BeatSaverDownloader and lots of other mods are still not loaded. only a few mods loaded with this workaround.

Are the mods incompatible with 1.6.0?

**Comment by FIocker** [comment]
Yea this isn't even working a little bit.

**Comment by Emblin13** [comment]
To add on to this, it turns out the fix hasn't done much for me either. Some mods work, such as NoFailCheck and PerfectionDisplay, but other mods such as ChromaLite are not working.

**Comment by Blenderpics** [comment]
The mods are placed correctly into the plugin folder.
The BeatSaber log is showing that all mods  are being loaded.
So it looks like ModAssistant did its job.

I guess we have to open issues in the repositories of the mods that are not working correctly, since it's not the fault of the ModAssistant

**Comment by FIocker** [comment]
Could be BSIPA's fault.

Am Di., 7. Jan. 2020 um 14:35 Uhr schrieb Blenderpics <
notifications@github.com>:

**Comment by Blenderpics** [comment]
I don't think its BSIPA's fault. If BISPA had trouble injecting something it would most likely write it to the log.

I will try and investigate this a bit further this evening.
