### ISSUE TITLE
Some mods not available/don't show up in Mod Assistant

### ISSUE THREAD

**Issue by aidanbeckley** [Assistant/ModAssistant#62]
Since not too long ago, the option to add Custom Avatars, Custom Platforms and Custom Sabers (and maybe some others) is not appearing in the Mod Assistant, most of the others, including Customs notes are available though. I used to be able to access all of these, but recently can't. I have tried reinstalling both the game and Mod Assistant and the problem is not resolved. Forgive me if this is due to updating them because of the update to Beat Saber.

**Comment by Andrew1431** [comment]
It's based on the Game Version. My guess is that these mods are not updated yet and as such do not appear in the mod assistant.
