### ISSUE TITLE
Trouble During Install

### ISSUE THREAD

**Issue by CandiSAHM** [Assistant/ModAssistant#63]
Hi.  The installer is unable to find my beat saber install folder.  However, when I find it manually, it does not allow me to select it.  It simply continues to open the folder I select instead of accepting the selection. I can't choose a folder, so I can't continue with installation.

**Comment by skylinelock** [comment]
I found a solution for this.

According to [this](https://github.com/Assistant/ModAssistant/blob/e4631efbb19395b27547c9e9ce0e061b3eaf8281/ModAssistant/Classes/Utils.cs#L138), InstallDir is Util#GetOculusDir's return value.
So looking into Util#GetOculusDir, this method will search registry key "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Oculus VR, LLC\Oculus\Config\" for Oculus installation path.
And the InstallDir variable will be the value of "InitialAppLibrary".

So if you changed the default oculus installation path to F drive, for example, the value of "InitialAppLibrary" is "F\Oculus\Software"

You can now launch ModAssistant.exe.
