### ISSUE TITLE
 I'm new with Beat Saber and mods.

### ISSUE THREAD

**Issue by r3dka** [Assistant/ModAssistant#70]
So excuse me if I might sound dumb.
Recently I've installed Your ModAssistant.
It was all OK until today when devs decided to make an update.
Of course STEAM does not offer "do not update" option anymore.
Because of that, the game seemed to be cleaned and all my songs went to hell.

Is this normal?
Whole CustomSongs folder is out...

Thank You for Your understanding.

PS. I get that mods will be available some time in the future. Is there any way I can roll back to previous version... or maybe trick the game to use modes from older version?

**Comment by wardy484** [comment]
I had a similar problem. I think SongCore compatibility broke with the latest update as a result uninstalling all mods brought back my custom songs. Then I selectively re-installed mods. until it worked correctly. Excluding ones that caused issues.

**Comment by r3dka** [comment]
Can You play now? As I dont see any mods for version  1.6.1.

**Comment by ShadowMax** [comment]
> Can You play now? As I dont see any mods for version 1.6.1.
Same. I cold find this guide: https://steamcommunity.com/sharedfiles/filedetails/?id=1805934840
I'll go and try to instal 1.6.0 version.

**Comment by r3dka** [comment]
I managed to roll back and install mods. One click doesn't work and I'm not sure where and how I should put the custom songs manually.

**Comment by ShadowMax** [comment]
> I managed to roll back and install mods. One click doesn't work and I'm not sure where and how I should put the custom songs manually.

use this guide it worked for me
https://www.youtube.com/watch?v=wIiRFhS5k14

**Comment by r3dka** [comment]
I've managed to find all songs that has been deleted during upgrade.
They were here: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data

My problems have been resolved. ThanYou for Your help ShadowMax and wardy484.

This issue can now be closed.
