### ISSUE TITLE
Mods for BS 1.6.1 are not showing up on Mods list on V 1.0.28

### ISSUE THREAD

**Issue by MobileRez** [Assistant/ModAssistant#71]
Using Steam BS and version 1.6.1 has nothing listed for Mod Assistant, yet when i hit install or update, it seems mods are there or in partial working form. which is to be expected things may break each time a new version comes out with beat saber. the mods id be questioning seem to be updated or in the process of being updated already.

Mod Assistant log: https://p.teknik.io/pEBAV

in the log i see things like:

[WARNING @ 01:18:40 | IPA/LibraryLoader] Could not add DLL directory

[WARNING @ 01:18:40 | IPA/LibraryLoader] System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified.

and

[CRITICAL @ 01:19:12 | UnityEngine] <>c__DisplayClass2_0:<Enqueue>b__0()

[CRITICAL @ 01:19:12 | UnityEngine] HMMainThreadDispatcher:Update()

[CRITICAL @ 01:19:12 | UnityEngine] MissingMethodException: void CustomPreviewBeatmapLevel..ctor(UnityEngine.Texture2D,StandardLevelInfoSaveData,string,IAudioClipAsyncLoader,IImageAsyncLoader,string,string,string,string,string,single,single,single,single,single,single,EnvironmentInfoSO,EnvironmentInfoSO,BeatmapCharacteristicSO[])

[CRITICAL @ 01:19:12 | UnityEngine] SongCore.Loader+<>c__DisplayClass80_3.<RetrieveAllSongs>b__3 () (at <b138edc79e74448fb3ea849e7997ce9b>:0)

[CRITICAL @ 01:19:12 | UnityEngine] HMMainThreadDispatcher+<ActionCoroutine>d__4.MoveNext () (at <4f69082cfe2449d8a4c10ce04918ab48>:0)

[CRITICAL @ 01:19:12 | UnityEngine] UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <4b072c28d0804e3e8741f43de2d5aec4>:0)

[CRITICAL @ 01:19:12 | UnityEngine] UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)

[CRITICAL @ 01:19:12 | UnityEngine] <>c__DisplayClass2_0:<Enqueue>b__0()

[CRITICAL @ 01:19:12 | UnityEngine] HMMainThreadDispatcher:Update()

Let me know if you need more info or need me to attach anything else to this to help.

**Comment by dal00** [comment]
I think this is because there are no approved mods on https://beatmods.com/#/mods for 1.6.1 currently

**Comment by MobileRez** [comment]
hmm okay. that explains the missing list, not sure about the errors and if they belong here or somewhere else. the mod assistant list seems to assume there will always be mods listed for the version. I wonder if a "no mods found for game version" message might be a feature to add if possible... didn't know about the site @dal00 only been playing the game after a few days and modded after the first as I didn't really want to shell out 71$ for a list of new songs, most of which i was not interested in playing. now I'm getting into level building and all that so i really appreciate these tools!

**Comment by Blenderpics** [comment]
you can downgrade beatsaber to 1.6.0 until there are mods available for 1.6.1. 
For the steam version, follow this tutorial: 
https://steamcommunity.com/sharedfiles/filedetails/?id=1805934840

**Comment by GeckoEidechse** [comment]
While the period until the first mods get updated isn't long, I do agree with @MobileRez that if no mods are available for the current version there should be some text saying so.

While we're at it, maybe also a message for when ModAssistant cannot connect to [beatmods.com](https://beatmods.com/) should the server be down, or the connection somehow else broken.

**Comment by Assistant** [comment]
> While the period until the first mods get updated isn't long, I do agree with @MobileRez that if no mods are available for the current version there should be some text saying so.
> 
> While we're at it, maybe also a message for when ModAssistant cannot connect to [beatmods.com](https://beatmods.com/) should the server be down, or the connection somehow else broken.

That's a good idea regarding showing a text that there's no mods available for a version, however that's the one part of the codebase I don't fully understand, so if anyone wants to provide a PR for it I can look at it.

And AFAIK there is a message if BeatMods can't be contacted.

**Comment by MobileRez** [comment]
@Assistant sorry for the delay in replying. has this already been added? If not, I can try and take a look and see if its something I am able to make a PR for when able.

**Comment by Assistant** [comment]
It has not been added, this issue only happens when a large update that break mods happens, and only until mods start getting updated, which is usually very fast. The infrequency of this issue makes it not be on top of my priority list, so a PR would be welcome.
