### ISSUE TITLE
Crash during attempt of removing the mods/BSIPA

### ISSUE THREAD

**Issue by S-ed** [Assistant/ModAssistant#72]
When IPA.exe is missing from the folder Mod Assistant will crash on the attempt of checking its version.
It happens during "Remove All Mods" or "Uninstall BSIPA" action.

To reproduce:
- Delete IPA.exe manually
- Run Mod Assistant
- In Options click one of the buttons - "Remove All Mods" or "Uninstall BSIPA"

I've noticed it after 1.6.1 released and "Install or Update" button was grayed out.
So the solution was to Change the game version to 1.6.0 and refreshing the page, so the button got active again letting you reinstall the IPA so it can be removed.

![screenshot 1578526663](https://user-images.githubusercontent.com/3008353/72025403-11471180-3289-11ea-8fbe-b0580e34db92.png)

**Comment by Parapass** [comment]
it's gonna fail. first, it looks for BSIPA, and it uses IPA to uninstall bsipa and mods.
![image](https://user-images.githubusercontent.com/59424861/77824514-951ad800-70d9-11ea-82f8-42990b1ff134.png)

**Comment by megalon** [comment]
I've confirmed and labeled this as a bug.
Clearly Mod Assistant should check for BSIPA before trying to uninstall it, but the simple solution here is to install BSIPA though MA before trying to uninstall all mods or BSIPA.
