### ISSUE TITLE
Mac executable available 

### ISSUE THREAD

**Issue by dov0211** [Assistant/ModAssistant#75]
Is there any Mac OS executable available for this mod?

**Comment by Assistant** [comment]
There isn't and there probably won't be there for the foreseeable future unless someone has expertise in that area and helps with it. However, on linux it runs on wine, so it might work on Mac OS too.

**Comment by razorrider7** [comment]
How were you able to get this to work with wine? I've been stumped on how to get it running for the past few hours...
