### ISSUE TITLE
Duplicated Data Sheet At Mods Tab

### ISSUE THREAD

**Issue by Co2333** [Assistant/ModAssistant#77]
See screenshot.

![TIM截图20200125175007](https://user-images.githubusercontent.com/25259084/73119328-39c64f80-3f9b-11ea-9677-2ba12514e46c.png)

Logs here. https://p.teknik.io/tqX9h

**Comment by Parapass** [comment]
https://github.com/Assistant/ModAssistant/issues/84#issuecomment-583873021

**Comment by Assistant** [comment]
Fixed in v1.1.0
