### ISSUE TITLE
won't allow selection of game version 1.6.2 (current version)

### ISSUE THREAD

**Issue by mgmmd** [Assistant/ModAssistant#78]
Mod Assistant won't allow selection of game version 1.6.2 (current version), it only goes to 1.6.1 and when I try to play the game it just crashes.

**Comment by locant23** [comment]
I'm having the same problem doesnt give me ghame option 1.6.2

**Comment by Assistant** [comment]
Mod Assistant doesn't dictate what versions are available, [BeatMods](https://beatmods.com) does.
