### ISSUE TITLE
Survey get re-ticked by default despite Save Selected Mods enabled

### ISSUE THREAD

**Issue by Proulxs** [Assistant/ModAssistant#81]
This is very cash money of you, but not very user-friendly :(

**Comment by Uber2013** [comment]
+1

**Comment by Parapass** [comment]
https://github.com/Assistant/ModAssistant/blame/master/ModAssistant/Pages/Mods.xaml.cs#L30

**Comment by megalon** [comment]
Closing because the survey is no longer in MA
