### ISSUE TITLE
Crash while attempting to install mods

### ISSUE THREAD

**Issue by C4TSCR47CH** [Assistant/ModAssistant#82]
After selecting all the mods I want installed, and hitting the 'install or update' button, the status bar goes to "Installing BSIPA" then crashes, with the following error message.
![error](https://user-images.githubusercontent.com/53673146/73339564-e15ab080-422d-11ea-9c59-ab565e1cf70e.PNG)

I have tried doing this after a fresh install of Beat Saber, and having wiped the entire folder, and the same issue still occurs. I have even tried installing BSIPA manually, and the Mod Assistant doesn't seem to recognize it.

I have also ran the Mod Assistant as an administrator, and even tried using the 'Uninstall BSIPA' button, which just returns 'BSIPA Uninstalled' but hasn't done anything to the game files and has the same crash as before. I have the install folder set up properly, and have even tried running the program from inside the same hard drive as where the game is stored, in case it was an issue with that, same issue.

**Comment by VlaDexa** [comment]
Had the same problem, but after a restart of ModAssistant it dissapeared

**Comment by megalon** [comment]
Is this issue still occurring for you?

**Comment by megalon** [comment]
Possibly related to #67

**Comment by megalon** [comment]
Likely resolved with #130
