### ISSUE TITLE
Mod list loads twice if you click on "Mods" button while the mod list is loading

### ISSUE THREAD

**Issue by scowalt** [Assistant/ModAssistant#84]
1. Open application
2. While the mod list is loading, click on the mods button
3. Wait for mod list to finish loading

Expected: when the mod list is finished loading, each mod appears once

Actual: when the mod list is finished loading, each mod appears twice

![image](https://user-images.githubusercontent.com/1100550/74107026-d999e680-4b20-11ea-8402-529bcde48b0f.png)

**Comment by Assistant** [comment]
That's a known bug, and it'll be fixed in the next big update
