### ISSUE TITLE
One-click not working (missing await)

### ISSUE THREAD

**Issue by ecm85** [Assistant/ModAssistant#91]
One-click is not currently working. I debugged the app and the root cause is that the async code is missing an await. InstallAsset is async void, which means it doesn't properly wait for the call to finish and the app dies before it can install. This prevents both sabers and songs from installing.

The fix is simply to change InstallAsset to async Task, and then the calls to it in App.xaml.cs need to await it, which means ArgumentHandler needs to become async too. ArgumentHandler is called from Application_Startup, which is already async, so it's a pretty trivial fix.

I can submit a PR if you'd prefer. Just let me know.

**Comment by Assistant** [comment]
Thanks for finding the issue, I've been hearing about it but didn't have the time to investigate. I'd appreciate a PR
