### ISSUE TITLE
ModAssistant stopped working with wine

### ISSUE THREAD

**Issue by Corben78** [Assistant/ModAssistant#94]
Today ModAssistant is crashing for me with this error:

![grafik](https://user-images.githubusercontent.com/8013933/75818715-ae11c100-5d99-11ea-9f5c-55ff39fa96a9.png)

I created a fresh wine prefix, installed dotnet461 again via winetricks, but it didn't help. I can select the Beat Saber directory then, but as soon as it's selected above error occurs.

I tried this also on an older install, and even there is crashes now. I tried wine 4.21 (was working fine before) and wine 5.0. Also older versions of ModAssistant now crash on this (e.g. v1.0.30)

Any ideas?

**Comment by Assistant** [comment]
I believe this might be caused by a windows specific function I used. Can you try seeing if this build works?
[ModAssistant.zip](https://github.com/Assistant/ModAssistant/files/4283603/ModAssistant.zip)

**Comment by Corben78** [comment]
The version in your zip does indeed work. Thanks!
